### ISSUE TITLE
Overlay z-index is in pixel

### ISSUE THREAD

**Issue by sbelzile-nexapp** [TheComputerM/svelte-materialify#10]
The Overlay index property is injected as pixels in the DOM.

Steps to reproduce:
1. Go to https://svelte-materialify.vercel.app/components/app-bar/
2. Find the NavigationDrawer, make it active
3. right-click + inspect element on the overlay

The index property is exported as `--s-overlay-index: 3px;`, which is then picked up by the `z-index` property as follow: `var(--s-overlay-index);`

This makes the property not really being used.

Expected output: should render as `--s-overlay-index: 3;`

Workaround: use the style property of the component: `style="z-index: 3"`.

**Comment by TheComputerM** [comment]
Fixed in v0.1.7: https://github.com/TheComputerM/svelte-materialify/commit/e352b7aeaa25138947d95a1e963af583e4501ab0
