### ISSUE TITLE
Menu component not present in d.ts file

### ISSUE THREAD

**Issue by unlocomqx** [TheComputerM/svelte-materialify#104]
The IDE shows this warning
<img width="496" alt="2021-01-18 at 9 05 AM" src="https://user-images.githubusercontent.com/793712/104888068-86552880-596c-11eb-932b-2e40328bfcd5.png">

Code
`import { Button, Card, CardActions, CardText, CardTitle, Dialog, List, ListItem, Menu } from "svelte-materialify";`

The Menu component is missing from index.d.ts as far I as checked

**Comment by Florian-Schoenherr** [comment]
Fixed by #86
