### ISSUE TITLE
Use restProps on Dialog

### ISSUE THREAD

**Issue by unlocomqx** [TheComputerM/svelte-materialify#106]
Hi,

The dialog doesn't preserve passed attributes

Example
``` html
<Dialog bind:active data-cy="add-project-dialog"></Dialog>
```

I don't know if it's the only component that doesn't preserve the attributes, I will discover these as I go
Cheers

**Comment by TheComputerM** [comment]
> $$props references all props that are passed to a component, including ones that are not declared with export. It is not generally recommended, as it is difficult for Svelte to optimise.
> $$restProps shares the same optimisation problems as $$props

So we generally do not do this.

**Comment by unlocomqx** [comment]
Okay, I will use classes as an alternative then
Thanks
