### ISSUE TITLE
 add snowpack config example

### ISSUE THREAD

**Issue by nerdoc** [TheComputerM/svelte-materialify#107]
In you Readme.md, you have support for rollup and webpack, could you add support for snowpack to? Just an example. Thanks!

**Comment by TheComputerM** [comment]
You can use svelte-materialify with snowpack also, just add the preprocess option to snowpack-plugin-svelte for advanced installation.

**Comment by nerdoc** [comment]
Eh, yes, I thought so. But I couldn't wrap my head around the config - and how to set this. I'm a newcomer to bundling/packaging, even webpack was a complete chaos for me - and I can't really understand which options belong to which object etc. - Documentation of rollup and snowpack are not the best here.
I added the example `svelte.config.js` and tried to integrate it into `snowpack.config.js`:
```
const { preprocess } = require('./svelte.config');
/** @type {import("snowpack").SnowpackUserConfig } */
module.exports = {
  //...
  packageOptions: {
    rollup: {
      plugins: [
        svelte({ preprocess }),
        require("rollup-plugin-svelte")({
          include: ["./node_modules"],
        }),
    //...
```
I tried 100 versions of (un)nesting the objects, no combination worked. I always get the `ReferenceError: svelte is not defined` - which is clear, as there is no `svelte` object in snowpack config per default. But I couldn't find it in the rollup docs, or enywhere else, besides your example.
Sorry - I'm sure that's a small thing, but I really don't know how to solve this - maybe you just give me a hint towards a direction.
If you want I could write a PR for including the snowpack config inyour README, as othery maybe struggle here too...?

**Comment by PeufOne** [comment]
You just need to install svelte manually `npm install svelte`.

If you want, you can use this [starter template](https://github.com/PeufOne/start) which also use Routify.

**Comment by Florian-Schoenherr** [comment]
See #132

**Comment by betaboon** [comment]
> I added the example `svelte.config.js` and tried to integrate it into `snowpack.config.js`:
> 
> ```js
> const { preprocess } = require('./svelte.config');
> /** @type {import("snowpack").SnowpackUserConfig } */
> module.exports = {
>   //...
>   packageOptions: {
>     rollup: {
>       plugins: [
>         svelte({ preprocess }),     //   <---- WTF?
>         require("rollup-plugin-svelte")({
>           include: ["./node_modules"],
>         }),
>     //...
> ```
> 
> I tried 100 versions of (un)nesting the objects, no combination worked. I always get the `ReferenceError: svelte is not defined` - which is clear, as there is no `svelte` object in snowpack config per default. But I couldn't find it in the rollup docs, or enywhere else, besides your example.

@nerdoc even tho the aproach you have been trying to take is wrong when using snowpack, I'll adress the error:
the `svelte` you are trying to reference here is actually `import svelte from 'rollup-plugin-svelte';` which you implicitly already do with `require("rollup-plugin-svelte")({....})`

> You just need to install svelte manually `npm install svelte`.
@PeufOne that doesn't adress the error described.


in general:
the `minimal installation` is currently possible with snowpack by just using `@snowpack/plugin-svelte` as described in the snowpack documentation [here](https://www.snowpack.dev/tutorials/svelte)

the `advanced installation` is currently not possible with snowpack due to a limitation within snowpack as described in #132

**Comment by Florian-Schoenherr** [comment]
@nerdoc is this still needed? There's a sveltekit setup now + this problem might be gone

**Comment by nerdoc** [comment]
Sorry, I moved away from Svelte for the moment (went to Django sockpuppet). So For me, you can close this issue.
