### ISSUE TITLE
Documentation of some components is a 404

### ISSUE THREAD

**Issue by nerdoc** [TheComputerM/svelte-materialify#108]
In the Materialify docs, when you click on "Virtual Lists", you get a 404:
https://svelte-materialify.vercel.app/components/virtual-lists/

**Comment by nerdoc** [comment]
Same with "Mutate": https://svelte-materialify.vercel.app/actions/mutate/
(seen at the bottom of https://svelte-materialify.vercel.app/actions/intersect/ - the "mutate box"

Il put that into the same issue, as it should be easy to fix together.

**Comment by RobertWeaver** [comment]
Carousel is also not found.

seen at the bottom of https://svelte-materialify.vercel.app/components/slide-groups/ 

https://svelte-materialify.vercel.app/components/carousels/

**Comment by TheComputerM** [comment]
Sorry for not replying earlier, these components are not complete yet but are planned to come.
