### ISSUE TITLE
Display helper not working properly

### ISSUE THREAD

**Issue by devYusuf** [TheComputerM/svelte-materialify#109]
Hello, j just tried out this framework and was doing some examples from the docs.
So I tried out the display helpers, e.g `d-md-none` and all other display are not working properly for their respective breakpoints.

Any solution?

**Comment by Florian-Schoenherr** [comment]
If you have time, could you provide a small example? I just tried it really quickly (added class="d-md-none" to the body of the docs) and it worked.

**Comment by Florian-Schoenherr** [comment]
Closing this, please comment if there's still a problem.
