### ISSUE TITLE
Slider not working for decimal value

### ISSUE THREAD

**Issue by kapilbhavsar** [TheComputerM/svelte-materialify#112]
Slider doesnt not works for values
min = 0.0
max = 1.0
step = 0.1
the values set by slider are 0 and 1 only instead of 0.1, 0.2, 0.3

**Comment by TheComputerM** [comment]
I am not seeing an error:
```html
<script>
	import {MaterialApp, Slider} from 'svelte-materialify'
</script>

<MaterialApp>
	<Slider min={0} max={1} step={0.1} />
</MaterialApp>

```

**Comment by Florian-Schoenherr** [comment]
Note: Could be fixed by exposing noUiSlider's `format` option

**Comment by weepy** [comment]
i also have this issue ? Is there a work around ?
