### ISSUE TITLE
/styles/reset/ errors after reloading page

### ISSUE THREAD

**Issue by Florian-Schoenherr** [TheComputerM/svelte-materialify#115]
`Uncaught (in promise) TypeError: Cannot read property 'content' of undefined`
https://svelte-materialify.vercel.app/styles/reset/

**Comment by TheComputerM** [comment]
Are you sure? this is not a problem for me.

**Comment by Florian-Schoenherr** [comment]
with chrome87
![image](https://user-images.githubusercontent.com/65456722/106734420-49975b80-6613-11eb-8c03-db550ca3b804.png)
I haven't found any call to `.content` or something.

**Comment by TheComputerM** [comment]
I am on brave browser chromium version 88, let us check if anyone else has this issue.

**Comment by Florian-Schoenherr** [comment]
![image](https://user-images.githubusercontent.com/65456722/106736358-a431b700-6615-11eb-96bd-7a23d836fa54.png)
inside the gumshoe code

**Comment by Florian-Schoenherr** [comment]
> can't reproduce on firefox-85, google-chrome-88, brave-88

> it is an error when the content in body is not loaded and the right nav spy is activated, the spy is controlled by gumshoe

> so somewhere it's not passing something in fast enough / passing nothing

**Comment by Florian-Schoenherr** [comment]
I think gumshoe is dead, this is apparently fixed since 2019: https://github.com/cferdinandi/gumshoe/pull/111

btw I think it happens because the spy assumes there are items? (seems to happen when gumshoe loads before content is available, have also tested with an empty `.md` file: there the content loads but it always gives back the error (possibly because there are no headers (#toc a's?) present)

**Comment by marekdedic** [comment]
I can confirm this on FF 86.
Basically, if a page is too short, gumshoe breaks. The workaround is to make the page longer.

**Comment by Florian-Schoenherr** [comment]
@marekdedic thank you! Does the fix in my PR work on your end? There's a vercel preview.

**Comment by marekdedic** [comment]
Sorry, haven't tried it. IMHO, vendoring it in is a bad architectural decision... Maybe use an alternative like https://www.npmjs.com/package/menuspy?

**Comment by Florian-Schoenherr** [comment]
@marekdedic thank you for the hint, you're right. Will have to see how the API differs, I just wanted the most basic fix for now.
