### ISSUE TITLE
Hello world 500 error :(

### ISSUE THREAD

**Issue by csaltos** [TheComputerM/svelte-materialify#12]
I tried the code at the docs with the getting starting steps with Sapper and I get this error when trying to run dev:

<S.MaterialApp> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules

Please find a repo with the error to reproduce here -> https://github.com/csaltos/sapper-svelte-with-materialify ... the commit with the attemped changes is at [96cbecb](https://github.com/csaltos/sapper-svelte-with-materialify/commit/96cbecbc0600c4b2476f072963b457d7bb9b833d)

I hope you can help us with it.

Thanks you Mudit for your code, it's pretty cool !!

**Comment by csaltos** [comment]
OK, thanks to Mudit it's now fixed !! ... please find the fix at [e373411](https://github.com/csaltos/sapper-svelte-with-materialify/commit/e373411e482188f0d75569254010570defcb3134).

There is a reference repo that helps too -> https://github.com/TheComputerM/sapper-materialify-template

**Comment by TheComputerM** [comment]
Yes, I think this has been fixed https://github.com/TheComputerM/svelte-materialify/issues/13, I will soon introduce a method that allows sapper to take in precompiled js files for SSR rendering rather than the source files which might speed up the build/development process.

**Comment by csaltos** [comment]
Thank you very much Mudi !! 👍❤️❤️
