### ISSUE TITLE
Remove/deprecate deprecated keypress event from TextField

### ISSUE THREAD

**Issue by fourhundredfour** [TheComputerM/svelte-materialify#121]
Since it is marked as `deprecated`/`legacy` in the current [UI Events Specification](https://www.w3.org/TR/uievents/#event-type-keypress) it shouldn't be used as the only option to receive a key event.

To avoid breaking changes I didn't remove the `keypress` event.

Useful resources:
https://www.w3.org/TR/uievents/#event-type-keypress
https://caniuse.com/?search=keypress
https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event

**Comment by Florian-Schoenherr** [comment]
Closed by #122
