### ISSUE TITLE
Components with transitions should forward transition events

### ISSUE THREAD

**Issue by frankieali** [TheComputerM/svelte-materialify#124]
I'd like to add an event when a dialog has finished revealing itself. The component has a transition prop, but none of the transition events are available to hook into. I think any component with a transition should have the transition events forwarded.

```
<div role="document" class="s-dialog" use:Style={{ 'dialog-width': width }}>
    <div
      class="s-dialog__content {klass}"
      class:fullscreen
      transition:transition={{ duration: 300, start: 0.1 }}
      on:introstart
      on:outrostart
      on:introend
      on:outroend
    >
         <slot />
    </div>
</div>
```

**Comment by Florian-Schoenherr** [comment]
Do you want transition options as a prop too?

**Comment by frankieali** [comment]
Transition options sound like a nice to have feature, but I don't really need it at the moment and it could open the door to additional UI bugs. I would just stick with the transition events for now. Thanks
