### ISSUE TITLE
Minor Bug - transition:slide choppy / laggy

### ISSUE THREAD

**Issue by dmitrioligy** [TheComputerM/svelte-materialify#127]
Cards > Custom Actions > Button (shows detailed information)
Currently docs and demo are using using:
```
{#if condition}
<div class='padding'>
    some text
</div>
{/if}
```
Will cause the padding to immediately show, and cause transition to jagged. 
Then the text appears smoothly resizing the container. 

I found the fix to be by simply adding another container - transition will make this the basis of the growth ease-in-out (assuming).

This seems to be the fix: (Double check me on that)
```
<div transition:slide>
    <div class="padding">
        {description}
    </div>
</div>
```

**Comment by Florian-Schoenherr** [comment]
Have I understood this correct? I think this even is how svelte wants it.
```
{#if active}
<div transition:slide>
  <Divider />
  <div class="pl-4 pr-4 pt-2 pb-2">
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Expedita autem,
    asperiores dolores, doloremque ea atque suscipit dolore, ut adipisci amet possimus
    dicta at voluptas consequatur!
  </div>
</div>
{/if}
```
You can make a PR with that! 😉
([keep contrib guideline in mind](https://svelte-materialify.vercel.app/getting-started/contributing/#submit-your-change))

**Comment by dmitrioligy** [comment]
Yes, I omitted the {#if} in the correct 2nd code snippet. Your code snippet is correct. I may try a PR if I have time. Minor, but can be a hiccup for anyone not familiar with it.
