### ISSUE TITLE
Imports need the /src directory explicitly

### ISSUE THREAD

**Issue by csaltos** [TheComputerM/svelte-materialify#13]
This is rather a minor tweak but maybe worth an improvement ->

**CURRENT BEHAVIOUR:**

When importing a component with something like:

`import { Button } from "svelte-materialify";`

it fails with a 500 error on the browser ... but if you import with `"svelte-materialify/src"` it works.

**EXPECTED BEHAVIOUR:**

Support aliasing for importing without requiring the extra `/src`

**Comment by TheComputerM** [comment]
This is needed for sapper, see [Advanced Installation](https://svelte-materialify.vercel.app/getting-started/installation/#advanced-install). Sapper needs the source files to compile them into SSR templates.
