### ISSUE TITLE
Multiple Badges

### ISSUE THREAD

**Issue by tonprince** [TheComputerM/svelte-materialify#130]
Is there a way to show multiple icons on a component, multi badge?

**Comment by Florian-Schoenherr** [comment]
What are you going for?
I had multiple badges beside eachother once and just used.. multiple badges :)

**Comment by tonprince** [comment]
I have a use case where I need to show 2 icons on a button widget and thought I could realize that with the Badges component.

**Comment by Florian-Schoenherr** [comment]
You can do what's shown in the examples, just with 2 Badges and then adjust with the `offsetX`/`offsetY` props, right?
