### ISSUE TITLE
Missing on:change event on Select component

### ISSUE THREAD

**Issue by tonprince** [TheComputerM/svelte-materialify#131]
It would be very helpful to have an onChange-event available on the select component.

**Comment by Florian-Schoenherr** [comment]
In your local `node_modules` folder, can you try changing our `Select.svelte`, adding
`on:change` [on the TextField here](https://github.com/TheComputerM/svelte-materialify/blob/31e1ae2426578e5627d9bd08277724fa5da42082/packages/svelte-materialify/src/components/Select/Select.svelte#L36)? The TextField already forwards the event, so if Select also forwards it and it actually updates correctly on your end, that would be good :)

**Comment by tonprince** [comment]
That I already tried, but unfortunately without success. I created a possible solution in a pull request with a click event on the list item which triggers a change event.

**Comment by romanown** [comment]
on:change event activated on open and on select (changing) or close (repeat click on the Select) the Select component.
on REPL it show in the console.
[https://svelte.dev/repl/e525bec5970a401f9b48fe45313fcbd7?version=3.35.0](https://svelte.dev/repl/e525bec5970a401f9b48fe45313fcbd7?version=3.35.0)
