### ISSUE TITLE
How do I make the NavigationDrawer in the AppBar page, clip under the AppBar?

### ISSUE THREAD

**Issue by ChrisMGeo** [TheComputerM/svelte-materialify#135]
In this [link](https://svelte-materialify.vercel.app/components/app-bar/) under the example titled Navigation Drawers, the Navigation Drawer's contents are not visible, due to it being below the AppBar. Is it possible to clip the NavigationDrawer to be under the AppBar(in terms of the y-axis, and not the z-axis), so that all it's contents are visible without blocking out the AppBar itself. Yes, the user can get out by clicking outside the NavigationDrawer, but I don't think that's really all that great, in use and in terms of appearance.

**Comment by Florian-Schoenherr** [comment]
I labeled this bug, but maybe there is no better way than this:
You can specify the z-index on the `NavigationDrawer`.

In the docs, we should either do that or do it like the docs navbar:
![image](https://user-images.githubusercontent.com/65456722/107920333-13d86800-6f6d-11eb-9c36-beaeb0173920.png)
