### ISSUE TITLE
Any way of binding whether or not a ListItemGroup has a selected ListItem?

### ISSUE THREAD

**Issue by ChrisMGeo** [TheComputerM/svelte-materialify#138]
I want to display certain elements only when a `ListItem` has been selected, within a `ListItemGroup`, is it possible to add a binding (or if there is any please do tell me), which binds whether or not a `ListItem` is selected. Moreover, is there a feature like a hypothetical `on:activation` for a `ListItem`, so that when it becomes active, we can execute a function?
Sorry for the ramblings in this issue.

**Comment by Florian-Schoenherr** [comment]
`ListItem` has an on:click event forwarded, but there's no on:change on `ListItemGroup`, if you mean that.
You could wrap that pretty easily I think. And you can bind to `Listitem.active` and react to that.
Depending on what you're doing, `ListGroup` could help, too.

**Comment by ChrisMGeo** [comment]
Thanks will see what I can do.
