### ISSUE TITLE
Sass variables override options?

### ISSUE THREAD

**Issue by adikdev5** [TheComputerM/svelte-materialify#139]
Hi. 
Is there any way to override the theme variables, like [svelte material ui does](https://github.com/hperrin/svelte-material-ui/blob/master/site/src/theme/_smui-theme.scss)?
https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/styles/_variables.scss

I could not find reference and could not make it work with _material-theme.scss.
I appreciate if I could get some guidance here. Thanks

**Comment by Florian-Schoenherr** [comment]
after setting up advanced install it [should work like this](https://svelte-materialify.vercel.app/getting-started/usage/#theming):

- [_material-theme.scss](https://github.com/vlingo/vlingo-schemata/blob/fef8e681f5af3216b39768226d40deceb1248e00/src/main/frontend/theme/_material-theme.scss#L1)

- [importing variables in a style tag](https://github.com/vlingo/vlingo-schemata/blob/fef8e681f5af3216b39768226d40deceb1248e00/src/main/frontend/src/routes/_layout.svelte#L89)

- try removing cookies / clearing cache of the site, too

**Comment by adikdev5** [comment]
Yes. I tried that way, but it is not global, I have to do the import every page.

For example, if I want to change font-family and primary-color globally, Svelte material UI let us do just by adding _smui-theme.scss and have variable override there. We don't need to do the import in page level.

**Comment by Florian-Schoenherr** [comment]
@adikdev5 you overwrite inside the `_material-theme.scss`. That's global. It's basically the same as in SMUI
