### ISSUE TITLE
Question about CSS Reset/ress

### ISSUE THREAD

**Issue by NiemandTV** [TheComputerM/svelte-materialify#14]
The documentation mentions that materialify uses ress to reset CSS properties, but I've noticed that this gets only applied to the components it provides, not to the whole project/app. Is there any way to change that without having *two* CSS resetters in one project?

**Comment by TheComputerM** [comment]
Can you provide a repro using a REPL, if the `MaterialApp` component is included in the App, the reset css should take effect.

**Comment by NiemandTV** [comment]
Sure, here are a few examples: https://svelte.dev/repl/e9912cf236c14564928e7dff42ce4cd1?version=3.28.0

**Comment by TheComputerM** [comment]
Those styles have been added by svelte materialify itself
- [paragraph](https://github.com/TheComputerM/svelte-materialify/blob/d4310c7f74e54cc84c0667baa85ee61c118c082b/packages/svelte-materialify/src/styles/elements/_global.scss#L22)
- [lists](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/styles/elements/_lists.scss)

**Comment by TheComputerM** [comment]
You can use margin helper classes to change the margin and padding. (doc page coming soon)
