### ISSUE TITLE
Tooltip stuck on the dom even if the component was removed

### ISSUE THREAD

**Issue by darkcris1** [TheComputerM/svelte-materialify#140]
See the image below even after the parent of the component is removed the tooltip still on the screen

![Tool stuck](https://user-images.githubusercontent.com/65588059/108686127-f6d50380-752f-11eb-9ae7-85e02c804336.png)

Try it here:

https://svelte.dev/repl/e84f9f49ba4a479296ad5d80a371db6a?version=3.32.3

**Comment by betaboon** [comment]
initial investigation:
seems like `Tooltip`-component is missing `onDestroy`

**Comment by darkcris1** [comment]
Yeah, I notice that too, there is no cleanup after appending the tooltip on the body. Maybe I will create a pull request later to fix this
