### ISSUE TITLE
Clicked Button shows black outline when tailwindcss is installed

### ISSUE THREAD

**Issue by microdou** [TheComputerM/svelte-materialify#143]
### Issue:
With `tailwindcss` set up, a clicked Button displays black outline.

### Screenshot:
Without `tailwindcss`:
![image](https://user-images.githubusercontent.com/8561307/108760080-31807100-751b-11eb-8a41-05a241666e00.png)

With `tailwindcss`:
"Hello World" correctly shows shadow per `tailwindcss` style tag `shadow-2xl` , proving the `tailwindcss` is setup correctly. However, button shows unwanted black outline in Chrome, and dotted outline in Firefox.
Chrome:
![image](https://user-images.githubusercontent.com/8561307/108760606-e024b180-751b-11eb-93dc-2b8901dcaaff.png)

Firefox:
![image](https://user-images.githubusercontent.com/8561307/108760684-f599db80-751b-11eb-86f0-cfe26c2ecbb5.png)

### How to Reproduce:
Without `tailwindcss`:
https://github.com/microdou/svelte-test/tree/svelte-materialify-button
With `tailwindcss`:
https://github.com/microdou/svelte-test/tree/svelte-materialify-button-tailwindcss

``` sh
git clone https://github.com/microdou/svelte-test
cd svelte-test

# test button without tailwindcss
git checkout svelte-materialify-button
npm i
npm run dev
# Then open up browser at http://localhost:5000
# Click the button, button style should be fine

# test button with tailwindcss
git checkout svelte-materialify-button-tailwindcss
npm i
npm run dev
# Then open up browser at http://localhost:5000
# Click the button, button style is ruined by black outline
```
### Browsers:
The issue is tested on both Firefox & Chrome.

**Comment by darkcris1** [comment]
That is not an issue, It was built-in  style by the browser. You can remove that by adding to your global css

```css
button:focus {
  outline: none;
}
```

**Comment by microdou** [comment]
@darkcris1 Thanks! Your solution works! Interesting the addition of `tailwindcss` automatically added this style...
