### ISSUE TITLE
Dark Theme not full height

### ISSUE THREAD

**Issue by onlyspike** [TheComputerM/svelte-materialify#145]
I have just set up the theme in a new project from the sapper template.

https://github.com/TheComputerM/sapper-materialify-template

I then set the theme to dark, but for some reason the dark background is not full screen.
What would be the reason for that?

![image](https://user-images.githubusercontent.com/7235301/109014928-4563d880-76bd-11eb-8b70-7e43a6f014c9.png)

I have marked the white space with an X.

**Comment by Florian-Schoenherr** [comment]
You need to set your root (where sapper is injected) to `height: 100%` or maybe `min-height: 100%`

**Comment by Florian-Schoenherr** [comment]
Closing this, if you still have the problem, you might understand what I mean by looking at the height styling on this page:
https://svelte-materialify.vercel.app/styles/reset/
(Which also had white space, we solved it with the above mentioned)
