### ISSUE TITLE
primary-color

### ISSUE THREAD

**Issue by weepy** [TheComputerM/svelte-materialify#147]
how do i go about setting the primary-color ?

**Comment by spideythewebhead** [comment]
I am having the same problem, I am setting 
$primary-color: red;
In _material-theme.scss, but it's ignored .

When setting 
.primary-color { background-color: red important! }
It's working.  Is this the correct way;

**Comment by Florian-Schoenherr** [comment]
The [docs](https://svelte-materialify.vercel.app/getting-started/usage/#theming) show you how to do it, will look like [this](https://github.com/vlingo/vlingo-schemata/blob/fef8e681f5af3216b39768226d40deceb1248e00/src/main/frontend/theme/_material-theme.scss).

**Comment by spideythewebhead** [comment]
It doesn't work if you use snowpack. Just in case

**Comment by moisesbites** [comment]
I am stating a new project with Sapper, and I follow the instructions in https://svelte-materialify.vercel.app/getting-started/installation/

```
npx degit "sveltejs/sapper-template#rollup" md
cd md
npm i
npm i -D svelte-materialify svelte-preprocess sass postcss
touch svelte.config.js
mkdir -p theme
touch theme/_material-theme.scss
```

In `_material-theme.scss` I put, for example:
```
// Put your custom sass variables here
$primary-color: #00753b;
$secondary-color: #acd164;
$accent-color: #b78bc0;
$error-color: #e64325;
$warning-color: #ffa336;
$info-color: #acd164;
$success-color: #009d4b;
```

But the result is not what I expected. Maybe, custom theme is not working or I made something wrong.

In _layout.svelte I put:
```
<script>
  import { MaterialApp } from "svelte-materialify";
  let theme = "light";

  function toggleTheme() {
    if (theme === "light") theme = "dark";
    else theme = "light";
  }

  //export let segment;
</script>

<MaterialApp {theme}>
  <main>
    <button on:click={toggleTheme}>Toggle Theme</button>
    <slot />
  </main>
</MaterialApp>
```

In the index.svelte I put for test:
```<script>
</script>

<svelte:head>
  <title>Sapper project template</title>
</svelte:head>

<!-- backgrounds -->
<div class="red">Red</div>
<div class="yellow lighten-4">Light yellow</div>
<div class="deep-purple accent-1">Deep Purple</div>
<div class="primary-color">Primary</div>

<!-- text -->
<div class="red-text">Red</div>
<div class="yellow-text text-lighten-4">Light yellow</div>
<div class="deep-purple-text text-accent-1">Deep Purple</div>
<div class="primary-text">Primary</div>

<div style="line-height:10px">
  <h1 class="text-h1">Heading 1</h1>
  <h2 class="text-h2">Heading 2</h2>
  <h3 class="text-h3">Heading 3</h3>
  <h4 class="text-h4">Heading 4</h4>
  <h5 class="text-h5">Heading 5</h5>
  <h6 class="text-h6">Heading 6</h6>
  <div class="text-subtitle-1">Subtitle 1</div>
  <div class="text-subtitle-2">Subtitle 2</div>
  <div class="text-body-1">Body 1</div>
  <div class="text-body-2">Body 2</div>
  <div class="text-button">Button</div>
  <div class="text-caption">Caption</div>
  <div class="text-overline">Overline</div>
</div>
```
But, the colors not change.

**Comment by Florian-Schoenherr** [comment]
@moisesbites try `import { MaterialApp } from "svelte-materialify/src";`.
We will soon make it more clear how this works. Basically `svelte-materialify` is compiled, `svelte-materialify/src` uncompiled (so you can change variables)

**Comment by pmutshipayi** [comment]
> @moisesbites try `import { MaterialApp } from "svelte-materialify/src";`.
> We will soon make it more clear how this works. Basically `svelte-materialify` is compiled, `svelte-materialify/src` uncompiled (so you can change variables)

Hey, after doing this it working like a charm but vscode is complaining about types and I lose all the autocomplete am working with typescrypt, << Could not find a declaration file for module 'svelte-materialify/src'.  >> how can overcome this issue ????

**Comment by Florian-Schoenherr** [comment]
@pmutshipayi wait for next release (1.3.8, which will soon be on npm) see #174
