### ISSUE TITLE
Several ListGroups in List & keeping states

### ISSUE THREAD

**Issue by arjarn** [TheComputerM/svelte-materialify#15]
I've several ListGroups in a List to simulate a panel component (thanx for your past help for make it).

I want to keep open / close states for ListGroup in my panel.
When I close my panel ( = collapse all ListGroup ), I need, keep all states and restore them when my panel is open again.

All is OK with variables binding on active properties except slide effect :-/

If I close panel and open it, slide effect is fire and jerky effect appear.

REPL with the problem : 

[https://svelte.dev/repl/b02a7c9d5dc74874a4c4d51520448e8a?version=3.29.0](url)

You can reproduce if you close panel and open it.

PS : collapsing is buggy in REPL but working fine in my project...

**Comment by TheComputerM** [comment]
Do you want something like the left navigation drawer on https://svelte-materialify.vercel.app/getting-started/installation/ ?

**Comment by arjarn** [comment]
Almost... :)  
If I take left navigation drawer, my problem is : if you open "Component" section and after opening "Groups" section.
I need, if I'm closing "Component" Section and re-open it, having "Groups" section always open.

Seem it's ok with ListGroup except the slide effect.

**Comment by TheComputerM** [comment]
There are some bugs with svelte, when they are resolved, ListGroup will be somewhat revamped.

**Comment by TheComputerM** [comment]
I think this is solved now.
