### ISSUE TITLE
Installation with Sveltekit

### ISSUE THREAD

**Issue by arjarn** [TheComputerM/svelte-materialify#150]
I'm attempting install svelte-materialify with Sveltekit using snowpack@next and plugin-svelte@next but I have this error :  

_[snowpack] ! building dependencies...
[snowpack] Failed to load node_modules/svelte-materialify/src/components/Grid/Container.svelte
  Try installing rollup-plugin-svelte and adding it to Snowpack (https://www.snowpack.dev/tutorials/svelte)
[snowpack] Dependency Install Error: Install failed._

My package.json is  : 

```{
{
	"name": "ejd-next",
	"version": "0.0.1",
	"scripts": {
		"dev": "not-svelte-kit dev",
		"build": "not-svelte-kit build",
		"start": "not-svelte-kit start"
	},
	"devDependencies": {
		"@snowpack/plugin-svelte": "^3.1.0-pre.7",
		"@sveltejs/adapter-node": "next",
		"@sveltejs/kit": "next",
		"@sveltejs/snowpack-config": "next",
		"not-svelte-kit": "0.0.7-next.34",
		"postcss": "^8.2.6",
		"sass": "^1.32.8",
		"snowpack": "^3.1.0-pre.10",
		"svelte": "^3.29.0",
		"svelte-materialify": "^0.3.5",
		"svelte-preprocess": "^4.6.9"
	},
	"type": "module"
}
```
and my svelte.config.cjs :

```
const sveltePreprocess = require('svelte-preprocess');

module.exports = {
	kit: {
		// By default, `npm run build` will create a standard Node app.
		// You can create optimized builds for different platforms by
		// specifying a different adapter
		adapter: '@sveltejs/adapter-node',

		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte'
	},
	preprocess: sveltePreprocess({
		scss: {
		  includePaths: ['theme'],
		},
	  })
};
```
This error appear after I modify my index.svelte with : 

_import * as S from 'svelte-materialify/src';_

**Comment by Florian-Schoenherr** [comment]
@arjarn can this be closed? Probably changed 50 times in the meantime 😄
