### ISSUE TITLE
after Advanced Install and importing the component Button colorise is not work

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#153]
i installed as docs Advanced Install. 
when i use: 
```
import { Button } from "svelte-materialify";
<Button class="primary-color">Primary</Button>
```
its work right but size of bundle js and css is very big.
![image](https://user-images.githubusercontent.com/7169357/110002244-3bc61a80-7d26-11eb-9b7a-8618bee4f3cb.png)

when i use

```
 import Button from "svelte-materialify/src/components/Button";
<Button class="primary-color">Primary</Button>
```

size of bundle decreaced but color of button not work.

is result html

`<button class="s-btn size-default primary-color s-ripple-container" type="button"><span class="s-btn__content">Primary</span></button>`

![image](https://user-images.githubusercontent.com/7169357/110000707-a70eed00-7d24-11eb-87f5-67f928618b2a.png)

link to REPL [https://svelte.dev/repl/a02a68ea811147fcbe8c1993c5fbe7b5?version=3.35.0](https://svelte.dev/repl/a02a68ea811147fcbe8c1993c5fbe7b5?version=3.35.0)

**Comment by Florian-Schoenherr** [comment]
[wrap it in MaterialApp](https://svelte-materialify.vercel.app/getting-started/usage/#layout).

**Comment by romanown** [comment]
but it increased size of the bundles as i used ` import { Button } from "svelte-materialify";`
how i can decreased size of bundles using only part of component?
