### ISSUE TITLE
Text Fields work is wrong when imported only is one.

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#154]
`import TextField from "svelte-materialify/src/components/TextField";`
when i imported as show. the project bundle sizes (js and css) is smiller but its wrong. title do not going to top when focus..

link to REPL [https://svelte.dev/repl/7cefe135751c4b089be75713c869b53c?version=3.35.0](https://svelte.dev/repl/7cefe135751c4b089be75713c869b53c?version=3.35.0)

**Comment by Florian-Schoenherr** [comment]
See #153

**Comment by romanown** [comment]
but it increased size of the bundles
