### ISSUE TITLE
Select after selected show value not name items

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#156]
1. when i selected item it show value in input field. in example page it work also.
![image](https://user-images.githubusercontent.com/7169357/110045631-04726080-7d5c-11eb-8270-6240edc9fefc.png)

2. items hide input field.
3. after changing (selected) item how send to function selected item value?

**Comment by romanown** [comment]
also in example page.
![image](https://user-images.githubusercontent.com/7169357/110045891-72b72300-7d5c-11eb-8c5b-c6a5b76e314c.png)
![image](https://user-images.githubusercontent.com/7169357/110045910-7a76c780-7d5c-11eb-86d5-42326f1af610.png)

**Comment by Florian-Schoenherr** [comment]
See #77

**Comment by romanown** [comment]
I'll wait for the new version. I hope the new version will be released soon.

**Comment by Florian-Schoenherr** [comment]
@romanown probably not, if you want, you can wrap our Select in your own, just [copy the SelectWrapper.svelte here](https://svelte.dev/repl/b30b98b3c0ea4f62842837a641eb71c4?version=3)

**Comment by romanown** [comment]
thank You very much

**Comment by romanown** [comment]
i to try work with the wrapper. when the data is fetching its not work. error 
`can't access property "name", items.find(...) is undefined`
[https://svelte.dev/repl/a02a2f6573cd4ff285197f606a2a02a5?version=3.35.0](https://svelte.dev/repl/a02a2f6573cd4ff285197f606a2a02a5?version=3.35.0)

**Comment by romanown** [comment]
i changed You wrapper to bypass error. but do not show initial value.
[https://svelte.dev/repl/1388014371024de2b9ed2ffc5f64f0dc?version=3.35.0](https://svelte.dev/repl/1388014371024de2b9ed2ffc5f64f0dc?version=3.35.0)

**Comment by Florian-Schoenherr** [comment]
it's a known bug, we want to release the fix asap. Please tell me after the next release

**Comment by romanown** [comment]
thanks. I hope that other problems that I wrote about will be fixed at the same time. the main problem that I can't continue using the package is showing the value instead of the name. to temporarily fix this problem, you made this wrapper. if you do not use this wrapper, everything works well even when loading data, but instead of the name, the value is shown.

**Comment by romanown** [comment]
i create the pull requst to fix this issue. if You can not use it can You to create the Select2 component and use my both pull for it?
`export let format = (val) => (Array.isArray(val) ? (val.map((vl) =>items.find((v)=>v.value==vl) ? items.find((v)=>v.value==vl).name : "no items").join(', ')) : (items.find((v)=>v.value == val) ? items.find((v)=>v.value == val).name : "no items" ));`
[](https://svelte.dev/repl/68079ea894674291b8766cadc087101e?version=3.35.0)

**Comment by romanown** [comment]
i can not create right pull request.  i not understand its errors. in REPL it work right. i fixed many times format but it find errors.
[https://github.com/TheComputerM/svelte-materialify/pull/189/](https://github.com/TheComputerM/svelte-materialify/pull/189/)

**Comment by Florian-Schoenherr** [comment]
I closed this because #77 is the same, you should discuss there. The format function is not telling me anything and due to ternary expressions mixed with arrow functions the linter complains.
Locally, you can run `yarn lint` and `yarn lint:fix` in the Root folder to find/fix linting errors.
