### ISSUE TITLE
can i use Paper as Material UI? and Block

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#159]
its i can or new futures Paper as Material UI. and can i do Block - it is Paper wrapped of Grid wrapped of children from props and having the title.
examlpe 
```
<Grid item xs={4} sm={4} md={props.size || 3}>
    <h4>{props.title}</h4>
    <Paper>{props.children}</Paper>
  </Grid>
```

**Comment by Florian-Schoenherr** [comment]
I don't understand. If you mean the Paper component from React's MaterialUI, we have a Card component.

**Comment by romanown** [comment]
the Paper have the header over component.
![image](https://user-images.githubusercontent.com/7169357/110206294-e3aa2800-7e8d-11eb-80d0-11ba655aa327.png)

**Comment by romanown** [comment]
ok. Card -> Paper. thank You.
