### ISSUE TITLE
Icon component doesn't render properly

### ISSUE THREAD

**Issue by fchpr** [TheComputerM/svelte-materialify#16]
An sample REPL: https://svelte.dev/repl/d141431d8b3d4c41bf95eb72106136cc?version=3.29.0

**Comment by TheComputerM** [comment]
If you want to use an icon webfont, you will have to first [import its CSS](https://svelte-materialify.vercel.app/components/icons/#types-of-icons). Or you can just use svg paths.
```html
<script>
	import { mdiHome } from '@mdi/js';
	import { MaterialApp, Icon } from "svelte-materialify";
</script>

<MaterialApp>
	<Icon size={32} path={mdiHome} />
</MaterialApp>
```

**Comment by fchpr** [comment]
My bad on this. Thank you for such a quick response!
