### ISSUE TITLE
(Select) on:change event activated on open

### ISSUE THREAD

**Issue by Florian-Schoenherr** [TheComputerM/svelte-materialify#162]
on:change event activated on open and on select (changing) or close (repeat click on the Select) the Select component.
on REPL it show in the console.
[https://svelte.dev/repl/e525bec5970a401f9b48fe45313fcbd7?version=3.35.0](https://svelte.dev/repl/e525bec5970a401f9b48fe45313fcbd7?version=3.35.0)

_Originally posted by @romanown in https://github.com/TheComputerM/svelte-materialify/issues/131#issuecomment-791929866_

**Comment by romanown** [comment]
perhaps this is no longer relevant and has been fixed?

**Comment by Florian-Schoenherr** [comment]
@romanown thanks for the reminder!
Fixed, [see REPL](https://svelte.dev/repl/1ea2d6376d8d4c67a796bfeb45bf9245?version=3.37.0).
