### ISSUE TITLE
(Select) bind:value is array

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#166]
when binding value of Select component it is give array. it show in console. i added object and string variable and same result.
REPL [https://svelte.dev/repl/16240a478f644f9d96381763dec532fc?version=3.35.0 ](https://svelte.dev/repl/16240a478f644f9d96381763dec532fc?version=3.35.0 )

**Comment by Florian-Schoenherr** [comment]
That's the current implementation, yes.

**Comment by romanown** [comment]
it is very problem when bind to text or digit value. can i have plain value?

**Comment by Florian-Schoenherr** [comment]
Can't you use on:change and don't bind?

**Comment by romanown** [comment]
I will be forced to do so. but the bind is more convenient and easier.

**Comment by Florian-Schoenherr** [comment]
@romanown you can still wrap the Select in you own mini component and then bind to that.
We want to redesign the Select, but that will take longer, for now this is good enough. Sorry!

**Comment by romanown** [comment]
sorry for the suggestion. but you can add a Select2 component and make it the classic behavior of the name and value. in this case, it will not break in existing projects and you do not have to wait for the new version.
