### ISSUE TITLE
Slider component does not seem to work

### ISSUE THREAD

**Issue by erokar** [TheComputerM/svelte-materialify#17]
Including a Slider component results in the following error in the console: Uncaught (in promise) Error: noUiSlider (14.6.1): create requires a single element, got: undefined

No slider shows up. Tested in Chrome and Firefox on MacOS, same behaviour in both browsers.

**Comment by TheComputerM** [comment]
Can you try this in a local project, the REPL is buggy sometimes.

**Comment by erokar** [comment]
This is in a local Svelte project, latest Materialify installed with npm, Parcel as bundler. Other Materialify components work.

**Comment by TheComputerM** [comment]
Can you try to do an [advanced installation](https://github.com/TheComputerM/svelte-materialify-template) and tell me, there is a problem with svelte hydrating the components.

**Comment by TheComputerM** [comment]
I think this has been fixed
