### ISSUE TITLE
data table

### ISSUE THREAD

**Issue by zfranco55** [TheComputerM/svelte-materialify#170]
i did not find a datatable with filter (global search) and select row, does it exist or is it missing?

**Comment by Florian-Schoenherr** [comment]
It is missing, I also think it's needed.

**Comment by zfranco55** [comment]
I hope it will be implemented.
for the moment that datatable, which has the selection of a row and a
gloobal filter, do you recommend me?

Il giorno ven 12 mar 2021 alle ore 10:07 Florian-Schoenherr <
***@***.***> ha scritto:

**Comment by Florian-Schoenherr** [comment]
I haven't used a datatable in svelte before, there are some implementations: https://github.com/search?q=svelte+datatable.
This one let's you define the table content, so you can do selection yourself pretty easily: https://vincjo.fr/svelte-simple-datatables/#/demo and it has global search, so you can filter.

**Comment by zfranco55** [comment]
Thanks!

Il giorno lun 15 mar 2021 alle ore 08:31 Florian-Schoenherr <
***@***.***> ha scritto:

**Comment by Florian-Schoenherr** [comment]
Closing this, duplicate of #58 
(now aware of global search+select row)
