### ISSUE TITLE
Not working with Svelte Kit (Vite)

### ISSUE THREAD

**Issue by dit7ya** [TheComputerM/svelte-materialify#171]
I am not sure if there is some special configuration to do with https://github.com/sveltejs/kit but this is the error I am getting when trying to use a simple Button component.

```
<Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules
```

**Comment by Florian-Schoenherr** [comment]
This is probably the Vite-Version of #132. I think I saw the same error on svelte discord, might be a problem with external components right now in general.

**Comment by dit7ya** [comment]
Updating to the given vite config makes that error go away but this new error pops up.

```
500

window is not defined

ReferenceError: window is not defined
    at /node_modules/svelte-materialify/dist/components/Slider/nouislider.min.js:6:8
    at /node_modules/svelte-materialify/dist/components/Slider/nouislider.min.js:7:3
    at instantiateModule (/home/sudraka/code/speaking-kit-new/node_modules/vite/dist/node/chunks/dep-e0f09032.js:68041:166)
```

**Comment by Florian-Schoenherr** [comment]
Can you try something? Slider is calling the nouislider stuff, so you can basically either wrap the call to nouislider in process.browser (or whatever it is in sveltekit) OR inside the nouislider code. If you don't know how/that doesn't work, you can try importing as specific as possible, so from 'svelte-materialify/src/components/Button/Button.svelte' (hope I got that right).

**Comment by dit7ya** [comment]
Yes. Importing in that very specific way works! However I was planning to eventually use the Slider component (very few component libraries provide it!). Let's see. Hoping to see everything stabilize soon.

**Comment by dit7ya** [comment]
Unfortunately I cannot see any styling at all. The button is just plain HTML button now. :(

**Comment by Florian-Schoenherr** [comment]
The problem is that we are using nouislider underneath, which calls window and Vite doesn't like calling window, I guess, because SSR? Maybe you can specify to not SSR for Slider? In sapper you could do `if(process.browser)`, or in this case it should also work if you do `if(window !== undefined)`.

Styling: huh, but maybe something like our Advanced Install is just not working in Vite right now.

**Comment by dit7ya** [comment]
Steps to reproduce the error

1. Create a project with `npm init svelte@next newProject`
2. Create a main.svelte file inside `src/routes/new.svelte` with the following content
```js
<script>
    import { Button } from "svelte-materialify/src/components/Button/Button.svelte";
    import { MaterialApp } from "svelte-materialify/src/components/MaterialApp/MaterialApp.svelte";
</script>

<MaterialApp theme="light">
    <Button class="red-text">Hello</Button>
</MaterialApp>

```
3. `npm run dev`
4. open `localhost:3000/new` in browser.

**Comment by Florian-Schoenherr** [comment]
You need to setup https://svelte-materialify.vercel.app/getting-started/installation/#advanced-install somehow, right? If there're no styles, preprocessing is missing probably

**Comment by Florian-Schoenherr** [comment]
https://github.com/sveltejs/kit/issues/231

**Comment by Liamolucko** [comment]
This seems to work with the following vite config:
```js
export default {
  ssr: {
    noExternal: ["svelte-materialify"],
  },
}
```

Because nouislider checks for `module.exports` before using `window`, if it's bundled (which is more or less what `noExternal` does) it never references `window`.

**Comment by gjovanov** [comment]
I had the same issue and I was able to fix it following suggesting from here:
[this](https://stackoverflow.com/questions/55745018/nouislider-es6-import)

By editing `node_modules\svelte-materialify\src\components\Slider\Slider.svelte`:

replacing: ~~`import noUiSlider from './nouislider.min';`~~ with `import * as noUiSlider from './nouislider.min';`

However, this solution is not tested for SSR mode.

Still, I hope you find it useful.

**Comment by Florian-Schoenherr** [comment]
@V-ed What's your config? Seems vite does it differently then rollup
