### ISSUE TITLE
Overide primary, secondary color (add to docs)

### ISSUE THREAD

**Issue by vladblindu** [TheComputerM/svelte-materialify#180]
Hello,
Thanks a lot for the library. 
I can't seem to figure out how to override the **theme colors** (primary, secondary, accent, etc)
I tried digging in the code, but when I reached the "svelte-preprocess" package, I gave up. 
I really hope, there's some stupid mistake I'm making, or there's something that hasn't landed in the docs yet so it won't take long putting me back on the track.

From the docs:
(relative to project root)
add a file:**"./theme/_material_theme.scss"** 
containing:
```scss
    $primary: #ff6666;
    $secondary: #002A69;
```
add a file **"svelte.config.js"**
containing:
```js
const sveltePreprocess = require('svelte-preprocess')

module.exports = sveltePreprocess({
    scss: {
        includePaths: ['theme']
    }
})
```
and request it in the **rollup.config** file:
```js

const preprocess = require('./svelte.config')

// pluginns
...
svelte({
            preprocess,
            emitCss: false,
            css: (css) => {
                css.write('bundle.css')
            }
        }),
...
```
In theory, this should do the trick, but if I add a **class="primary-color"** to the **AppBar** component,  I still get the this class in chrome dev-tools:
```css
.primary-color{
    background-color: #6200ee !important;
    border-color: #6200ee !important;
}
```
What am I missing?
Thanks again for your time and effort.

**Comment by Florian-Schoenherr** [comment]
[You missed `-color`](https://github.com/vlingo/vlingo-schemata/blob/fef8e681f5af3216b39768226d40deceb1248e00/src/main/frontend/theme/_material-theme.scss) :)

**Comment by Florian-Schoenherr** [comment]
https://svelte-materialify.vercel.app/getting-started/usage/#theming we should add that here.

**Comment by vladblindu** [comment]
Thank you so much. You should add a label "stupid mistake" :)).

**Comment by marekdedic** [comment]
Hi, sorry to piggyback on this issue, but I can't seem to get it working even when using the correct variables...

`src/frontend/App.svelte`:
```svelte
<MaterialApp>
  <AppBar class="primary-color">
    <span slot="title">
      Title
    </span>
  </AppBar>
</MaterialApp>

<script lang="ts">
  import {AppBar, MaterialApp} from 'svelte-materialify';
</script>
```

`theme/_material-theme.scss`:
```scss
// Svelte colors
$primary-color: #ff3e00;
$secondary-color: #676778;

:global(body) {
	color: red;
}
```

`webpack.config.js`:
```js
const HtmlWebpackPlugin = require("html-webpack-plugin");
const sveltePreprocess = require("svelte-preprocess");

const path = require("path");

module.exports = {
  mode: "production",
  module: {
    rules: [
      {
        test: /\.svelte/,
        use: {
          loader: "svelte-loader",
          options: {
            preprocess: sveltePreprocess({
              tsconfigFile: "./frontend.tsconfig.json",
              scss: {
                includePaths: ["theme"],
              },
            }),
          },
        },
      },
    ],
  },
  resolve: {
    alias: {
      svelte: path.resolve("node_modules", "svelte"),
    },
    extensions: [".ts", ".js", ".svelte"],
    mainFields: ["svelte", "browser", "module", "main"],
  },
  entry: {
    index: "./src/frontend/index.ts",
  },
  output: {
    filename: "[name].js",
  },
};
```

However, the appbar is still the old colour (violet, should be orange). If I add `@import "_material-theme.scss";` to `App.svelte`, the red color is added to body, however, the primary color stays the same. Any help please?

**Comment by Florian-Schoenherr** [comment]
@marekdedic 
Try `import {AppBar, MaterialApp} from 'svelte-materialify/src';`, these are the uncompiled components.
That's mentioned in the docs, but maybe we should add a "don't forget"

**Comment by marekdedic** [comment]
@Florian-Schoenherr That works, thanks! I didn't get that from the docs - I've seen both of these in the docs, but they seemed kind of random - I didn't realize there was a difference - adding that explicitly to the docs may help us more clueless users :smile:

**Comment by Florian-Schoenherr** [comment]
@marekdedic do you think it should _just_ be mentioned here: https://svelte-materialify.vercel.app/getting-started/usage/#components
or should we put this on every page, maybe as a little alert / ?

**Comment by marekdedic** [comment]
I don't think it's necessary on every page. The one you link is good, I'd also put it on "Installation" - that's where you first encounter the two different ways of loading components, but the difference isn't explained ;)
