### ISSUE TITLE
Making groups such as ButtonGroup, ChipGroup and ListItemGroup.

### ISSUE THREAD

**Issue by TheComputerM** [TheComputerM/svelte-materialify#2]
Making easily flexible groups in svelte is a problem. The ButtonGroup component will have to communicate with the Button component. These are some solutions:

**Solution 1**: put all logic in onMount
This is not recommended as onMount logic is always slow.
```js
onMount(()=> { /* add event listeners to querySelectorAll('.s-btn') */ });
```

**Solution 2**: add extra logic to Button to interact with ButtonGroup.
This is not recommended as the Button component is already quite large and having the extra code when Button is not a part of ButtonGroup will make it slow.

**Solution 3**: make universal components to control all groups.
Two new components will be added:
- Group.svelte
- GroupItem.svelte

Then ButtonGroup will inherit from Group.svelte and add some settings relevant to Buttons only.

```html
<ButtonGroup>
    <GroupItem let:active>
        <Button {active}>Group Item 1</Button>
    <GroupItem>
    <GroupItem let:active>
        <Button {active}>Group Item 2</Button>
    <GroupItem>
    <GroupItem let:active>
        <Button {active}>Group Item 3</Button>
    <GroupItem>
</ButtonGroup>
```

**Solution 4**: make separate components such as ButtonGroupItem.
This would be like solution 3 but `GroupItem` and `Button` would be combined into a single component called `ButtonGroupItem`,

```html
<ButtonGroup>
    <ButtonGroupItem>Group Item 1</ButtonGroupItem>
    <ButtonGroupItem>Group Item 2</ButtonGroupItem>
    <ButtonGroupItem>Group Item 3</ButtonGroupItem>
</ButtonGroup>
```

A problem with this is that it would add some unnecessary components and making it more difficult to use as you have to replace Button with ButtonGroupItem inside every group.

I would like to know which solution do you think is better or if you have any other solutions.
I prefer solution 4.

**Comment by TheComputerM** [comment]
The purpose of ButtonGroup is to select Button and see their values with options such as `multiple` and `mandatory`, something like https://svelte.dev/repl/7dae7f254a2348d5ad42ad09d84a137f?version=3.24.1

**Comment by kolllor33** [comment]
I find solution 4 the most clean of them all. It's more readable and less code to add as someone who would uses the library.

**Comment by jasonlyu123** [comment]
Maybe solution 4 and provide a named slot act like solution 3 so you can still customize it?

**Comment by Florian-Schoenherr** [comment]
3 looks good, but 4 would be optimal, right? I don't know too much about how tree-shaking works, but with 4 you would only bundle what you actually use, right? "you have to replace Button with ButtonGroupItem inside every group" with current IDE's, this costs like 10 seconds, so it's fine :)

**Comment by TheComputerM** [comment]
Implemented solution 4.
