### ISSUE TITLE
ExpansionPanel not included in /@types folder

### ISSUE THREAD

**Issue by AngelRionCervi** [TheComputerM/svelte-materialify#201]
Hi, 

Maybe it's done on prupose but the /@types folder is missing both `ExpansionPanels` and `ExpansionPanel` declaration files, resulting in compilation errors with TS.

**Comment by Florian-Schoenherr** [comment]
You probably need to update svelte-materialify 👍 
https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/%40types/index.d.ts#L23
https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/%40types/ExpansionPanel.d.ts
