### ISSUE TITLE
Padding around the Expansion Panel content

### ISSUE THREAD

**Issue by nateshmbhat** [TheComputerM/svelte-materialify#202]
Expansion panel adds padding around the content of the expansion panel and i don't have a way to remove that padding.

its better to not add any padding or margin for slotted components without providing a way to remove or customize that padding.

**Comment by Florian-Schoenherr** [comment]
@nateshmbhat you're right.
And you can customize in _material-theme.scss:
https://github.com/TheComputerM/svelte-materialify/blob/c73767415d7726f7f37b5e058ff761ad7d9d8a52/packages/svelte-materialify/src/components/ExpansionPanels/ExpansionPanel.scss#L110

**Comment by nateshmbhat** [comment]
shall i raise a PR with padding removed ? we also have to consider doing the same for all the other components also.
 
margin and padding is something that needs to be added by user's component itself unless its a macro component with many functionalities (like a clock, modal or such components).

**Comment by Florian-Schoenherr** [comment]
@nateshmbhat I know, but this would break too much stuff, we don't know who uses what. The lib is getting rewritten, so it will be fixed there.
For now, if you really need this, you should customize it via the sass-variable (which you can also do inside a svelte component). I hope that's enough.

**Comment by nateshmbhat** [comment]
Alright makes sense 👍
Thanks :)
