### ISSUE TITLE
Getting zero '0' as the input value the first time when text input changes in a TextField.

### ISSUE THREAD

**Issue by nateshmbhat** [TheComputerM/svelte-materialify#205]
I am using TextField component as shown below and when i any text on the text field , the on:input event has the event.detail property set to "0". This is a bug. This only happens for the first change of text though. for the subsequent changes its correct.

I am using version : 0.3.9 

```
  <TextField
    outlined
    dense
    color="color-primary"
    value={text}
    type="text"
    on:input={e => text = e.detail}
    placeholder="https://api.example.com"
  >
    <b> Host name </b>
  </TextField>
```

I can't even use the text field 😢

**Comment by Florian-Schoenherr** [comment]
I would suggest just binding the value for now. This might even be a svelte error (we are just forwarding the event: https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/components/TextField/TextField.svelte#L104).
In your example, what's the initial value of `text`?

**Comment by nateshmbhat** [comment]
Initial value is "http://localhost:9090"

**Comment by romanown** [comment]
placeholder="https://api.example.com" is equivalent "http://localhost:9090"?
may be to helped for You create example on REPL?[https://svelte.dev/repl]( https://svelte.dev/repl)

**Comment by Florian-Schoenherr** [comment]
Wait, I just realized, this is a DOM Event, so of course there is no detail (or if svelte did somehow fill it in, it doesn't now):
[See this REPL](https://svelte.dev/repl/7d7c38fe74d746708b835a6fdfb0561b?version=3).
@nateshmbhat did this work somehow before? You could open an issue on the svelte repo.

**Comment by Florian-Schoenherr** [comment]
In the REPL you can also see that `e.target.value` exists and contains the whole word, so this IS a svelte bug.

**Comment by Florian-Schoenherr** [comment]
In the REPL you can also see that e.target.value exists.
