### ISSUE TITLE
there are no new changes in the package as well as on the REPL

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#214]
there are no new changes in the package as well as on the REPL [https://svelte.dev/repl/99f9c23dbde34516aae1ac67ef4ab587?version=3.35.0](https://svelte.dev/repl/99f9c23dbde34516aae1ac67ef4ab587?version=3.35.0)

**Comment by Florian-Schoenherr** [comment]
please provide a clear example

**Comment by romanown** [comment]
ok. [https://svelte.dev/repl/c86b6d8a202a4376b2dcf9219b22c34e?version=3.35.0](https://svelte.dev/repl/c86b6d8a202a4376b2dcf9219b22c34e?version=3.35.0)
the behavior of the select component is the same as it was before the changes were made a week ago. this may change after the version update.

**Comment by Florian-Schoenherr** [comment]
@TheComputerM another release is needed

**Comment by romanown** [comment]
I assumed that. I'll be waiting.

**Comment by romanown** [comment]
many thanks.
