### ISSUE TITLE
Hovering over buttons in AppBar is rectangular for short time

### ISSUE THREAD

**Issue by robsch** [TheComputerM/svelte-materialify#221]
This is also visible on the current AppBar on https://svelte-materialify.vercel.app/

Happens with Buttons in this structure:

```
<AppBar>
  <div slot="icon">
    <Button fab depressed>
      <Icon path={mdiMenu} />
    </Button>
  </div>
 ...
<AppBar>
```

Actually, I would let the hovering effect be rectangular in the AppBar. What would be a quick fix for the current version?

btw. the buttons make problems in the [dense AppBar](https://svelte-materialify.vercel.app/components/app-bar/) as well.

**Comment by Florian-Schoenherr** [comment]
@robsch what browser are you on?

**Comment by robsch** [comment]
I see this with Firefox on CentOS 8. Indeed, on my windows machine I don't see this effect in Firefox.

**Comment by Florian-Schoenherr** [comment]
hmmm.. can you provide a screenshot? Seems like an interesting issue.

**Comment by robsch** [comment]
Here is a small video. Taken from AppBar page:

https://user-images.githubusercontent.com/2900992/115373832-89122480-a1cc-11eb-8240-e01c64b305f7.mp4

**Comment by robsch** [comment]
I've seen the same issue also within a Footer, so it is not solely related to the AppBar. Probably, it has nothing to do with the containing element. Example:

<Footer fixed padless class="justify-center flex-column">
    <div class="mt-2 mb-2">
        <a use:link href="/faq">
            <Button text rounded>FAQ</Button>
        </a>
        <a use:link href="/colop">
            <Button text rounded>COLOP</Button>
        </a>
        <a use:link href="/terms-and-conditions">
            <Button text rounded>TERMS AND CONDITIONS</Button>
        </a>
        <a use:link href="/privacy-policy">
            <Button text rounded>PRIVACY POLICY</Button>
        </a>
        <a use:link href="/legal-information">
            <Button text rounded>LEGAL INFORMATION</Button>
        </a>
    </div>
</Footer>

**Comment by Florian-Schoenherr** [comment]
Hm, can you see this effect on any other implementations of material? (They should use a similar approach)
Check it on Vuetify for example.

**Comment by robsch** [comment]
Tried menu button [here](https://vuematerial.io/components/menu) and indeed there is the same effect. What does that mean?

**Comment by Florian-Schoenherr** [comment]
They are rectangles, but these are circles: https://vuematerial.io/components/menu/#menu-rich
I would guess it's a linux issue, maybe graphics driver bug? If it's only on centOS, might be related to that.
Never had experience with it, but it seems like it.

> I see this with Firefox on CentOS 8. Indeed, on my windows machine I don't see this effect in Firefox.

**Comment by robsch** [comment]
Okay. CentOS is in a VM. I've tried it wihin a Fedora machine (also a VM) and there all is fine. Yes, it might has something to do with graphic drivers in combination with the VM (VMWare Fusion on a MacBook). 

It might be fixable, but I'm not an expert regarding CSS and cannot do this. I'd say, svelte-materialify is not the source of the problem. You can close the issue if you don't want to do anything about it.

**Comment by Florian-Schoenherr** [comment]
It's probably not even css related, is what I mean 👍

**Comment by robsch** [comment]
I've got that. However, it might be fixable via CSS anyway. 

Egal ...  😉
