### ISSUE TITLE
Chip is not an exported member of 'svelte-materialify'

### ISSUE THREAD

**Issue by AmiterCodes** [TheComputerM/svelte-materialify#233]
as the title suggests, trying to import Chip from 'svelte-materialify' does not work while every other component I tried did,
seems that it doesn't have a type either in @types, probably needs to be fixed or added

**Comment by Florian-Schoenherr** [comment]
Seems like we don't have it as a type. Could you add it? Would be a simple copy-paste task from the [Chip itself](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/components/Chip/Chip.svelte) and other [types](https://github.com/TheComputerM/svelte-materialify/tree/master/packages/svelte-materialify/%40types). I don't have any time left today.

**Comment by AmiterCodes** [comment]
added pull request #244
