### ISSUE TITLE
Textarea Label issue

### ISSUE THREAD

**Issue by GrochowskiC** [TheComputerM/svelte-materialify#247]
class active is not applied on label because the labelActive variable is not reactive.
should have :   `$: labelActive = !!placeholder || value;`
instead of :   `let labelActive = !!placeholder || value;`

**Comment by V-ed** [comment]
It's supposed to be updated through these methods no?

https://github.com/TheComputerM/svelte-materialify/blob/02cf91ee9028abeb4dcfbb3ae6829c1892533e7c/packages/svelte-materialify/src/components/Textarea/Textarea.svelte#L44-L56

**Comment by GrochowskiC** [comment]
No. If the value is updated after initialization, by async data for example, labelActive will stay to false.
And to be consistent with the TextField component, you should use $:
(Also, to be consistent with TextField, use export validate() instead of checkRules and return error !)

**Comment by V-ed** [comment]
Ah, true, I see what you mean now

Example REPL : https://svelte.dev/repl/1154fe4b3434494b88c2e1cf35960c76?version=3.38.1

(notice how the label doesn't shift up as the "test" string value gets updated)
