### ISSUE TITLE
EOL Svelte Materialify

### ISSUE THREAD

**Issue by romanown** [TheComputerM/svelte-materialify#254]
Svelte Materialify is almost ready to work and fully functional. there's a little more work left in it. of course, here you decide, but I do not understand why spend time on a new one to completely go through the entire path of creation? and what should those who already use Svelte Materialify do and who are satisfied with it? in comparison with the others, in my opinion, Svelte Materialify is the best. will the new library be made better and smaller than the old one? how soon will the new library be ready for use? will there be full compatibility?

**Comment by TheComputerM** [comment]
I am not writing a new lib from scratch, most of the stuff will be copy pasted. Some components are getting a rewrite like TextField so that it can work with numeric inputs easily.

**Comment by TheComputerM** [comment]
The new lib will be smaller, faster and modular and will have more components leaving you to choose which components to install.

The dev experience will also be a lot better.

**Comment by romanown** [comment]
thanks. in that case, I'm happy to update. I wish you success in creating a new library.

**Comment by romanown** [comment]
if you consider it necessary I suggest closing this issue
