### ISSUE TITLE
Github sponsor / opencollective / pateron

### ISSUE THREAD

**Issue by filipot** [TheComputerM/svelte-materialify#30]
Hi! Does this project have any link to github sponsor / opencollective / pateron? I'm really impressed by this project. It is the prettiest component framework I have seen for svelte so far.
I would love to give 20$ a month to further incentivise the development of the project.

Thanks!

**Comment by TheComputerM** [comment]
I will add it when the docs are complete, till then if you can you can donate to svelte or an animal shelter 🐱 .
