### ISSUE TITLE
CONTRIBUTING.md is not helpful

### ISSUE THREAD

**Issue by paganaye** [TheComputerM/svelte-materialify#34]
I failed to compiling your app.
I can clone the whole project, see that there are 4 subprojects.
Trying to compile them one by one
 1 - svelte materialify : install success / build success
 2 - documentation: install fails, need api :-(
 3 - API : install : install success run api success
 4 - documentation : run dev again : cannot find module polka
... 
not much success
I think I need a better tutorial if you want me to help you code or write documentation

**Comment by TheComputerM** [comment]
Yeah will update the file, the process to compiling svelte materialify is.
- Run `yarn` at root of project
- Run `yarn build` to compile svelte materialify
- Run `yarn api` to build api json
- Run `yarn dev` to open documentation
