### ISSUE TITLE
select dropdown appear behind other controls.

### ISSUE THREAD

**Issue by paganaye** [TheComputerM/svelte-materialify#36]
In  this REPL
https://svelte.dev/repl/aaec9bbff21540aab79d507b692d3f36?version=3.29.0

The select dropdown list appear behind a button.

**Comment by TheComputerM** [comment]
I am modifying the CSS in devtools but cannot seem to get the Menu above the Button, have you had any luck with this?

**Comment by djotanov** [comment]
I think you will need to append menu component to body element. Than zindex will work. Otherwise zindex works only in parent component with relative positioning.

**Comment by paganaye** [comment]
Solution is below.
The z-index attribute only works on positioned elements.
So you have to set both the position and z-index.
Here I set the top bar in foreground with everything inside (including the buttons and drop downs) will appear in front of the main page.
```
  :global(.app-bar) {
    position: relative;
    z-index: 1;
  }
```
Perhaps you should put that within the component itself?
I would give you an updated repl, but repl doesn't work for me today.

**Comment by Florian-Schoenherr** [comment]
@paganaye 
I think that's the wrong REPL?
But the fix works, nicely done.
Fixed REPL:
https://svelte.dev/repl/5f3d4185f97e45ec953da32231d70d45?version=3.31.0
z-index should be 5, otherwise it clashes with the nav and `<Appbar fixed/>` is also 5.
