### ISSUE TITLE
Sample from the documentation crashes in REPL

### ISSUE THREAD

**Issue by paganaye** [TheComputerM/svelte-materialify#39]
Tabs sample copied from the documentation doesn't work in REPL

[Failing] Tabs sample from the documentation 
https://svelte.dev/repl/9038b32222604fe9aae5498a0f529011?version=3.29.0
Cannot read property 'querySelectorAll' of undefined

I wonder if the documentation would work better with just embedding REPL samples.

**Comment by TheComputerM** [comment]
This is the same problem as https://github.com/TheComputerM/svelte-materialify/issues/33 I am trying to figure out a workaround as mentioned [here](https://github.com/sveltejs/svelte/issues/5445). I am trying the workaround but [it is not working](https://github.com/sveltejs/component-template/issues/8#issuecomment-712347167)
