### ISSUE TITLE
Input slots: prepend-outer and append-outer need hiding when not in use

### ISSUE THREAD

**Issue by cliveportman** [TheComputerM/svelte-materialify#42]
Creating an input without any of these slots still renders the slot. Which means the slots' margin pulls in the sides of the input. We could:
- Identify whether the slot was not set or left empty, and not display it. My favourite option, though I'm not sure how easy that is.
- Somehow remove the margin if the slot is not set or left empty.
- Switch to using a variable instead of a slot. I quite like the fact you can insert HTML in there, tbh.

Something like (from https://github.com/sveltejs/svelte/issues/2106#issuecomment-501000254):
```
<script>
const SLOTS = $$props.$$slots
</script>
{#if (SLOTS['prepend-outer'])}<slot name="prepend-outer" />{/if}
```
Although, that doesn't work.

**Comment by TheComputerM** [comment]
Slot forwarding is here so we could do something with that.

**Comment by TheComputerM** [comment]
Done
