### ISSUE TITLE
<MaterialApp> is not a valid SSR component.

### ISSUE THREAD

**Issue by JeffWScott** [TheComputerM/svelte-materialify#43]
I followed the Sapper setup, all versions are the newest (as of today).

```
<script>
  import { MaterialApp } from 'svelte-materialify';
  let theme = 'light';
</script>

<MaterialApp theme="{theme}">
  <slot />
</MaterialApp>
```

The Layout section of the website tells me to use this code in my _layout.svelte file but when I do it throws this error.

**Error: <MaterialApp> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules**

**Comment by TheComputerM** [comment]
https://svelte-materialify.vercel.app/getting-started/installation/#advanced-install, please join our discord to ask questions. The minimal installation will be reworked in the next release so that you can use svelte materialify without any preprocessor.

**Comment by GiorgosK** [comment]
Same thing happens with svelte-kit latest and cannot be resolved with the workaround mentioned in https://github.com/TheComputerM/svelte-materialify/issues/87

Any ETA on when the library will be available to be consumed from sapper or svelte-kit ? 
thanks

**Comment by TheComputerM** [comment]
You can definitely use the library on sapper, don't know about svelte-kit.
