### ISSUE TITLE
Select cannot bind to non array value

### ISSUE THREAD

**Issue by edwindj** [TheComputerM/svelte-materialify#47]
Many thanks for this amazing library!

I ran into a small issue with <Select>: currently it is not possible to `bind:value` to a value that is not an array. the `format` function assumes that the `value` is an Array. 

So: 

``
<Select {items} {value}>My select input </Select>
``

fails when `value` is not an array.

Can be easily solved: PR coming in a minute.

**Comment by TheComputerM** [comment]
The select component only accepts an array, it will not accept a string or a number. This is done to provide an easy interface for multiple items, suppose if you have items `'foo','bar','buzz'` then the value would be something like `['foo']`. I personally do not like this, but if a user wanted to switch between multiple selectable values and single selectable values then there is no other way.

**Comment by edwindj** [comment]
Thanks for the clarification: I understand that the Select component supports multiple selections, but often (in my use case), there is a need for single selections. 

The current fix, does allow for binding to a "text", "number"  value. I was thinking that when `multiple == false` Select can bind to a text/numeric value and when multiple == true it binds to an Array.

**Comment by TheComputerM** [comment]
The problem is more than that, Select uses the ItemGroup (not currently documented) component and so checking if a value is active or not also needs to be changed then, if I find a performant way to this I will let you know.

**Comment by edwindj** [comment]
For sure I don't know the intricacies of the framework (which is great!), but my suggested fix seems to work, showing which item is selected.
I reckon you mean the ListItemGroup that binds to value? Does not seem to give a problem when binding with a text value. 

When I look into the source code (Select.svelte), the other cases where a non-array value causes problems are when multiple is true or when chips is true...

**Comment by TheComputerM** [comment]
Almost every selection component is handled by [this](https://github.com/TheComputerM/svelte-materialify/blob/abbe072776cd84cb43d4bbfde05bf0a34fbbb4d3/packages/svelte-materialify/src/components/ItemGroup/ItemGroup.svelte#L29) changing array to string would need a lot of rework. Also it may affect the performance, If this is a much requested feature, I will change it.

**Comment by Florian-Schoenherr** [comment]
@edwindj try this 👍

**Comment by TheComputerM** [comment]
I have fixed this using a cheeky internal hack, I may have forgotten to update a few examples so if you spot one, let me know about it.

**Comment by edwindj** [comment]
Thanks, much appreciated!
