### ISSUE TITLE
TextField uses flex / cursor: pointer outside container

### ISSUE THREAD

**Issue by Florian-Schoenherr** [TheComputerM/svelte-materialify#52]
![flex breaks](https://user-images.githubusercontent.com/65456722/98175158-57472300-1ef6-11eb-9a43-3393dc50de70.png)
form-structure:
```
<span class="d-flex">
  <TextField/>
  <Select />
  <Select />
  <Switch />
</span>
```
How would you solve this easily?
I tried adding the `.s-input`-class in my dev-console, which worked.
![now all baseline](https://user-images.githubusercontent.com/65456722/98175747-7a260700-1ef7-11eb-862d-c8614a70e68f.png)
It would be nice to have this as the default, or is there any downside to this?
This also worked:
![no flex at all](https://user-images.githubusercontent.com/65456722/98176049-16e8a480-1ef8-11eb-8edf-498b47384a15.png)

But with both of these "solutions" and also without any solution applied, there is still another problem:
![pointer two far](https://user-images.githubusercontent.com/65456722/98176213-66c76b80-1ef8-11eb-963f-f19e2120ea50.png)
The pointer-cursor gets set on `.s-select:not(.disabled)`, which, with this layout, is a far greater block than it should be.
I would like to fix this, but I don't have time right now.

**Comment by TheComputerM** [comment]
I do not see any error: https://svelte.dev/repl/dbcc052fa38348c2b313ec6d778d49e5?version=3.29.4

**Comment by Florian-Schoenherr** [comment]
I meant that's only the "structure".
REPL: https://svelte.dev/repl/563732c59869449cbcd8c91d9e874a9a?version=3.29.4

**Comment by TheComputerM** [comment]
Add class `align-start` to `d-flex`.

**Comment by Florian-Schoenherr** [comment]
`align-center` works even better. Thanks!

About the cursor-thing, this fixes it:
Delete:
`.s-select:not(.disabled)`
Add:
```
.s-select:not(.disabled) input, .s-select:not(.disabled) .s-menu__wrapper {
  cursor: pointer;
}
```
Could you add that to the scss, please?
