### ISSUE TITLE
Error with npm run dev (Svelte or Sapper)

### ISSUE THREAD

**Issue by arjarn** [TheComputerM/svelte-materialify#6]
Using installation procedure but when I'm running **npm run dev** having this trouble :

[!] (plugin svelte) ParseError: Unexpected input
node_modules\svelte-materialify\src\components\Grid\Container.svelte
11:   .s-container {
12:     width: 100%;
13:     padding: $container-padding-x;
                 ^
14:     margin-right: auto;
15:     margin-left: auto;
ParseError: Unexpected input
    at error (E:\my-svelte-project\node_modules\svelte\src\compiler\utils\error.ts:25:16)
    at Parser$1.error (E:\my-svelte-project\node_modules\svelte\src\compiler\parse\index.ts:100:3)
    at Object.read_style [as read] (E:\my-svelte-project\node_modules\svelte\src\compiler\parse\read\style.ts:21:11)

**Comment by TheComputerM** [comment]
Yeah 😂😂.
Actually the current version of svelte materialify publish on npm (v0.0.1) is just a test version, to reserve the name, I will be publishing the new version (v0.1.0) tommorow when I have completed the ListItemGroup component.

**Comment by TheComputerM** [comment]
Try changing the import path from `svelte-materialify` to `svelte-materialify/dist/index.mjs`.

**Comment by arjarn** [comment]
Thanx for your reply, actually I'm looking for good UI library and find 2 competitors : your and Smelte ;)

Best result with `svelte-materialify/dist/index.mjs` but :

```
Error: <MaterialApp> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled 
modules
```

**Comment by TheComputerM** [comment]
Released new version. Please check if you are having this problem and see that you are following the instructions in the README.

**Comment by arjarn** [comment]
Another attempt with this version :  `npm i svelte-materialify` with SAPPER

If I'm using <S.MaterialApp> in _layout.svelte page, I'm always having this :

` Error: <MaterialApp> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`

With using in "about page", no problem with that but when you're displaying page and return on other : 

`TypeError: outros is undefinedindex.mjs:872:8`

Error here : 

```
function transition_out(block, local, detach, callback) {
    if (block && block.o) {
        if (outroing.has(block))
            return;
        outroing.add(block);
        outros.c.push(() => {  // Error in this line 
            outroing.delete(block);
            if (callback) {
                if (detach)
                    block.d(1);
```

My code in "about.svelte" :


```
<script>
	import * as S from 'svelte-materialify';
</script>
<svelte:head>
	<title>About</title>
</svelte:head>

<S.MaterialApp>
	<h1>About this site</h1>
	<p>This is the 'about' page. There's not much here.</p>
	<S.Button class="primary-color">
		Button
	</S.Button>
</S.MaterialApp>
```

**Comment by TheComputerM** [comment]
@arjarn Please follow these instructions: https://github.com/TheComputerM/svelte-materialify#advanced-install. and then do:
```js
import * as S from 'svelte-materialify/src';
```

**Comment by TheComputerM** [comment]
Sorry for the unclear documentation, will add this to the README.

**Comment by arjarn** [comment]
No problem, I'm newbie with sapper so...

New fresh install with advanced install procedure.

My about page :

```
<script>
	import * as S from 'svelte-materialify/src';
</script>
<svelte:head>
	<title>About</title>
</svelte:head>

<S.MaterialAp>
	<h1>About this site</h1>
	<p>This is the 'about' page. There's not much here.</p>
</S.MaterialAp>
```

and the result : 

```
✗ server
/home/cdu/svelte/Sapper-Materialify/node_modules/svelte-materialify/src/components/Grid/Row.svelte
:global() must contain a selector
18:   margin-left: -4px;
19: }
20: .s-row.dense :global > .s-col {
                 ^
21:   padding: 4px;
22: }
✗ client
/home/cdu/svelte/Sapper-Materialify/node_modules/svelte-materialify/src/components/Grid/Row.svelte
:global() must contain a selector
18:   margin-left: -4px;
19: }
20: .s-row.dense :global > .s-col {
                 ^
21:   padding: 4px;
22: }
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/cdu/svelte/Sapper-Materialify/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

It seem, I forgot something....

**Comment by TheComputerM** [comment]
Did you install svelte-preprocess and sass?

**Comment by arjarn** [comment]
I made : 

`npm i -D svelte-materialify svelte-preprocess sass`

Creating ./theme/ with _material-theme.scss

and modify rollup.config.js.
Adding : 

`import sveltePreprocess from "svelte-preprocess";`

and :

```
const preprocess = sveltePreprocess({
	scss: {
	  includePaths: ["theme"],
	}
});
```

In Client section : 

```
export default {
	client: {
		input: config.client.input(),
		output: config.client.output(),
		plugins: [
			replace({
				'process.browser': true,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				preprocess,
				dev,
				hydratable: true,
				emitCss: true
			}), .........
```

and Server section : 

```
	server: {
		input: config.server.input(),
		output: config.server.output(),
		plugins: [
			replace({
				'process.browser': false,
				'process.env.NODE_ENV': JSON.stringify(mode)
			}),
			svelte({
				preprocess,
				generate: 'ssr',
				hydratable: true,
				dev
			}), ..........

```

**Comment by TheComputerM** [comment]
Looking into this bug rn.

**Comment by TheComputerM** [comment]
This seems to be a bug with svelte-preprocess, opening a issue there.

**Comment by TheComputerM** [comment]
https://github.com/sveltejs/svelte-preprocess/issues/249

**Comment by TheComputerM** [comment]
You can test your components over here: https://svelte.dev/repl/2c55788d8ffd4458bfe9bcb5f58956db

**Comment by arjarn** [comment]
Thanx for your support and your work

**Comment by TheComputerM** [comment]
Hey sorry, it seems that I missed one line of the documentation:
**You need postcss installed to get global styles to work**
Yous run `npm i postcss -D` and everything will be fine.

**Comment by TheComputerM** [comment]
See a demo template: https://github.com/TheComputerM/sapper-materialify-template

**Comment by arjarn** [comment]
All is right now. Can play with Sapper and svelte-materialify :)
