### ISSUE TITLE
Export checkRules() (or way to manually trigger validation) for TextField & Textarea component 

### ISSUE THREAD

**Issue by tokikanno** [TheComputerM/svelte-materialify#61]
ref discord conversation: https://discord.com/channels/768317529641975829/768317530162593804/776098583157669910

Sometimes I need to manually trigger validation rules

For example, in this repl: https://svelte.dev/repl/29b74bca4cfd4d3d9484c79c00357874?version=3.29.7

I want to lock my submit button by default if no required input has been provided. 

Of course, I could set the init error / disabled status by myself. But if there's any way I could trigger the validation rules manually, that I could have a consistent way for checking if I should disable the button or not.

The validateonblur option does work if the user has once clicked the TextField and exit, but won't work if no action has been taken.

**Comment by soft-decay** [comment]
A quick workaround would be to have an additional check on your `Button.disabled` state (see this [repl](https://svelte.dev/repl/9e6cb6bb37274345bbdcb26d49e64fd3?version=3.29.7))

An actual fix could be to have a prop (e.g. `validateImmediately`) to trigger `checkRules()` in `onMount()`, as in:

```svelte
<TextField 
  bind:value
  bind:error
  rules={[
    (v) => !!v || "required"
  ]}
  validateOnBlur
  validateImmediately
/>
```

**Comment by tomoam** [comment]
I got the same issue.

I need to manually trigger validation rules, like Vuetify.   
https://vuetifyjs.com/en/components/text-fields/#custom-validation

TextField of Vuetify has `validate` method with `Validatable` mixin.  
In the long run, it will be necessary to consider the specifications including Form, etc., but at this point, it is not that necessary.

How about renaming `checkRules` method to `validate` and export that?

For example,  
https://github.com/TheComputerM/svelte-materialify/compare/master...tomoam:master#diff-55db26d2c79c72d481dc04a0561e726f274c9732abf348e2576479b4a97ff166

I will make a PR if you are okay with this specification.

I'm sorry for my poor English.
Thanks

**Comment by Florian-Schoenherr** [comment]
@tomoam link doesn't seem to work, but please PR and rename it, yes. We will provide a `Form` component or something of that sort later.

**Comment by tomoam** [comment]
@Florian-Schoenherr 
Thank you for reply. I made the PR #117.
