### ISSUE TITLE
Demo Site Breaks When Selecting Already Selected Dropdown Value

### ISSUE THREAD

**Issue by jwsinner** [TheComputerM/svelte-materialify#62]
When previewing any component that has a dropdown menu (size, color, border, etc.) except for Breadcrumbs separator (which doesn't change when a new one is selected) the site will shut down. Clicking on different components will show in the url, but no change will happen. Scrolling to another component and trying to edit it will jump back to the faulty component. 

The error in the console is: Uncaught (in promise) TypeError: Cannot read property '0' of null

Gif attached.
![SvelteMaterialify](https://user-images.githubusercontent.com/4605954/99009730-c085f200-2505-11eb-9518-78cdd960106c.gif)

**Comment by TheComputerM** [comment]
Related to https://github.com/TheComputerM/svelte-materialify/issues/54

**Comment by rodgco** [comment]
@jwsinner Just left a comment at issue #54. There is a workaround by setting ```mandatory={true}``` at the Select component.
