### ISSUE TITLE
ParseError: Unexpected input

### ISSUE THREAD

**Issue by PortStone** [TheComputerM/svelte-materialify#64]
I just installed it as described here: https://svelte-materialify.vercel.app/getting-started/installation/#minimal-install
and copied to App.svelte this: https://svelte-materialify.vercel.app/components/app-bar/#usage

Error:
```
node_modules/svelte-materialify/src/components/Grid/Container.svelte
11:   .s-container {
12:     width: 100%;
13:     padding: $container-padding-x;
                 ^
14:     margin-right: auto;
15:     margin-left: auto;
ParseError: Unexpected input
```

Note: Since it didn't worked I tried out advanced install and now it works.

**Comment by TheComputerM** [comment]
What is your code?

**Comment by TheComputerM** [comment]
Replace svelte-materialify/src with svelte-materialify for minimal installation.

**Comment by PortStone** [comment]
Yep you are right. Didn't read the docs correctly.
