### ISSUE TITLE
Chip with button don't close

### ISSUE THREAD

**Issue by arjarn** [TheComputerM/svelte-materialify#7]
Hi,

I'm using chip with button inside and close option.
If I attempt close it, I'm having error.
I'm using your REPL for testing.

My simple code : 

```
	<S.Chip class="success-color" close>
		<S.Button size="x-small" rounded class="red-text mt-1 mr-2">Red</S.Button>
		 This is elegant chip !
	</S.Chip>
```

Question : have you in your futur plan, pagination component ?
EDIT : https://dev.to/haynajjar/responsive-svelte-tailwind-pagination-component-2o99

Thanx for your great work.

**Comment by TheComputerM** [comment]
Thanks for reporting the bug, looking into it, and as for a pagination component, yes I am looking to make it but it is on low priority as something like [this](https://svelte-materialify.vercel.app/components/slide-groups/) already exists.

**Comment by TheComputerM** [comment]
I think this is a bug with the REPL or something else as when I am testing it there is no problem.
![screencapture_com_2020-9-19_12_32](https://user-images.githubusercontent.com/24741538/93661395-16de3380-fa75-11ea-9a55-4ec5860a01b7.gif)

**Comment by arjarn** [comment]
Ok I made test with true install.

Thanx.

**Comment by TheComputerM** [comment]
So, is it working?

**Comment by arjarn** [comment]
it's working fine, sorry for this  issue and time losting
