### ISSUE TITLE
Moving @types folder to src folder

### ISSUE THREAD

**Issue by docseltsam** [TheComputerM/svelte-materialify#70]
I had problems adjusting the variables by overwriting them in the file theme/_material-theme.scss. Now I found out that this only works if I use 

import { ... } from 'svelte-materialify/src';

and not when I use 

import { ... } from 'svelte-materialify';

to import the Matrialify components. 

After changing the import path to svelte-materialify/src VS Code doesn't find the typescript definiton files anymore and there is no intellisense help anymore in the IDE. 

To solve this problem, I suggest to move the @types folder with the typescript defintions to the src folder.

**Comment by TheComputerM** [comment]
Would this make it work in both conditions stated above?

**Comment by docseltsam** [comment]
No, just for using 'svelte-materialify/src' as import path.

**Comment by docseltsam** [comment]
The package.json file has to be changed too. Tag "types" has to bei changed after moving to @types folder from

"types": "@types/index.d.ts",

to

"types": "src/@types/index.d.ts",

Afterwards you can use both import statements for typescript support. The changing of the theme just works if you use the

import { ... } from 'svelte-materialify/src'; 

statement.

**Comment by TheComputerM** [comment]
Can this problem be solved with `tsconfig`?

**Comment by docseltsam** [comment]
I'm not sure which problem you mean. 

The problem, that the typescript definitions are not found would be solved if the @types folder is moved to src folder and this path is set as value of types tag in package.json. Afterwards the definition files will be found either you use svelte-materialify or svelte-materialify/src.

On the other hand, the problem that the change of theme variables only takes effect if you use svelte-materialify/src is in my opinion no problem that is triggered by Typescript so I don't think that this can be solved by tsconfig.

**Comment by TheComputerM** [comment]
I don't know much about typescript but can the path be included in the `typeRoots`?

**Comment by docseltsam** [comment]
I didn't use this option so far, so I had to have a look at the documentation (https://www.typescriptlang.org/tsconfig#typeRoots). It doesn't seems to be a good idea, because this limits the used type definitions to exactly the paths given in typeRoots tag.

**Comment by docseltsam** [comment]
OK, I think I found a solution by adding a path tag to the tsconfig.json of my project. If you do this, you have to also add a baseUrl tag. My tsconfig.json now looks like this:

```{
	"extends": "@tsconfig/svelte/tsconfig.json",
	"compilerOptions": {
		"lib": ["DOM", "ES2017", "WebWorker"],
		"baseUrl": ".",
		"paths": {
			"svelte-materialify/src": ["node_modules/svelte-materialify/@types"]
		}
	},
	"include": ["src/**/*", "src/node_modules/**/*"],
	"exclude": ["node_modules/*", "__sapper__/*", "static/*"],
	"declaration": true
}```

It seems that this solves my problem, without moving the @types folder somewhere else. I will keep an eye on it.
