### ISSUE TITLE
fab conflicts with FontAwesome 5 .fab class

### ISSUE THREAD

**Issue by pouya-eghbali** [TheComputerM/svelte-materialify#74]
Can't use fab buttons with FontAwesome 5 due to the conflict, FA tries to render the buttons as icons.

Similar issue on other frameworks:
https://github.com/OnsenUI/OnsenUI/issues/2491
https://github.com/PygmySlowLoris/vue-fab/issues/21

**Comment by TheComputerM** [comment]
Can you show a REPL

**Comment by pouya-eghbali** [comment]
Here's the issue reproduced on Svelte REPL: https://svelte.dev/repl/4557b0026b3f4c98b04469fd2a45eeba

**Comment by Florian-Schoenherr** [comment]
Fixed by https://github.com/TheComputerM/svelte-materialify/commit/b713ef5d54ef127d450161513f2ef8ee75ea1333
