### ISSUE TITLE
Select displays item value instead of item name 

### ISSUE THREAD

**Issue by cendro93** [TheComputerM/svelte-materialify#77]
![image](https://user-images.githubusercontent.com/41925441/101002169-38bd6180-3560-11eb-898d-94fdee32c113.png)
I think it should display item name here. 
It should be 'Foo' not 'foo' 

This issue is visible on demo site: https://svelte-materialify.vercel.app/components/selects/

**Comment by TheComputerM** [comment]
The menu will display 'Foo' and the text field will display 'foo'

**Comment by cendro93** [comment]
Yes this is how it works now. But is it correct behavior ? 
Lets say i have smth like this(the value is an id for me):
const items = [
    { name: 'Bike', value: 1 },
    { name: 'Car', value: 2 },
    { name: 'Train', value: 3 },
 ];
How can i 'hold' hidden value of a 'Bike' which is 1 without showing it to a user ?

**Comment by docseltsam** [comment]
I would suggest to change the format function in Select.svelte as follows:

```
  export let displayName = false;
  export let format = (val) => (Array.isArray(val) ? val.reduce((a, c) => (!!a ? a + ', ' : '') + getDisplayValue(c), '') : getDisplayValue(val));

  function getDisplayValue(value) {
    if (displayName) {
      const i = items.findIndex(i => i.value === value);
      return i >= 0 ? items[i].name : value;
    } else
      return value;
  }
```

and add the getValue function to the Chips output:

```
          {#if chips}
            <span class="s-select__chips">
              {#each Array.isArray(value) ? value : [value] as v}
                <Chip>{getDisplayValue(v)}</Chip>
              {/each}
            </span>
          {/if}`
```
With that you can decide to show the value or the name in the TextField by specify the behaviour with the prop "displayName".

**Comment by bcholewinski** [comment]
This issue should be reopen. @TheComputerM

**Comment by TheComputerM** [comment]
Change the api where:
```js
{
name: "Foo", value: "internal-value"
}
```

`Foo` will be displayed in the dropdown and in the TextField when it is selected and `internal-value` will be returned to the program; this behavior can be changed of course. 👍🏼 if you agree.

**Comment by FunMiles** [comment]
The value being purely internal is consistent both with HTML's select and other frameworks I've used. I had to create a round-about trick to use the Select with the current implementation.

**Comment by Florian-Schoenherr** [comment]
Wow, so this was not intended, huh.

**Comment by romanown** [comment]
i tried minimize ternary but errors
`export let format = (val) => (Array.isArray(val) ? (val.map((vl) => items.find((v) => v.value === vl) ? items.find((v) => v.value === vl).name :  "no items").join(', '))  :  (items.find((v) => v.value === val) ? items.find((v) => v.value === val).name :  "no items" ));`
without ternary expressions should errors when the items is empty

**Comment by romanown** [comment]
great solution. we can use items = {name, value} or items = []. the best. thank You.
