### ISSUE TITLE
Missing types in the package

### ISSUE THREAD

**Issue by nchanged** [TheComputerM/svelte-materialify#78]
Hey, 
Currently, I have to do add this line to `index.d.ts` to make it stop complaining about missing types:

```
declare const Switch : any
declare const Tab : any
declare const Tabs : any
declare const TabContent : any
declare const Tooltip : any

export {Switch, Tab, TabContent, Tabs, Tooltip}
```

Is it possible to publish those?

**Comment by Florian-Schoenherr** [comment]
- [ ] Switch
- [ ] Tab
- [ ] Tabs
- [ ] TabContent
- [ ] Tooltip

**Comment by k4m1** [comment]
Adding these last 3 interfaces and the exports seems like something I could do. Could I pick these up?

**Comment by Florian-Schoenherr** [comment]
@k4m1 feel free :)
