### ISSUE TITLE
Question about styling...

### ISSUE THREAD

**Issue by arjarn** [TheComputerM/svelte-materialify#8]
I'm attempting build "Panel Style Menu" with custom style for header part (color or background image).
Like this : 

![image](https://user-images.githubusercontent.com/35603194/93764966-64dd6d80-fc14-11ea-999f-fa702b67da4b.png)

I'm using List (perhaps bad idea...) like :

```

<S.List dense class="ma-2 red elevation-2">
	<S.Subheader> .......... </S.Subheader>
	<div class="white">
		<S.ListItem>
			<span slot="prepend">
			      <S.Chip class="ma-2 primary-color">1</S.Chip>
			</span>
			Test
		 </S.ListItem>
	</div class="white">
</S.List>
```

Rendering is  : 

![image](https://user-images.githubusercontent.com/35603194/93762234-72442900-fc0f-11ea-8dc5-969f48839cb7.png)

I see, padding-bottom in List component :

![image](https://user-images.githubusercontent.com/35603194/93762302-91db5180-fc0f-11ea-92af-f87ca6f2ddd0.png)

It may be usefull if we can easily customise component. I know it's already possible with style and classes but avoid extra-padding / margin when possible will be great.

EDIT : attempt including Appbar in List, better result (and more clean) but having extra-padding in top :)

**Comment by TheComputerM** [comment]
Can you please provide a REPL example, I think you are using the wrong components.

**Comment by arjarn** [comment]
Please don't look collapsing : it isn't working with REPL.
All is ok but need style="padding 0"


https://svelte.dev/repl/2720c05474e943f18fd82969e7eeaec5?version=3.25.1

**Comment by TheComputerM** [comment]
Try this and tell me, the collapsing feature does not work in the REPL:
https://svelte.dev/repl/13f5a2cd8e2448caa555f14592895a55?version=3.25.1
Also see this: https://svelte-materialify.vercel.app/components/lists/#nested

**Comment by TheComputerM** [comment]
Padding and margin are a hassle, that is why we have helper classes for them.

**Comment by arjarn** [comment]
I'm trying your REP and it's not working (for collapse) but great idea having one specific ListItem for header. Nicer than my Navbar : sometimes, don't see simple solution. Thanx for this, I'm using your tips.

For collapsing, strange, all is ok if no REPL.

Agree for padding and margin.

**Comment by TheComputerM** [comment]
Yeah, the list not collapsing is the REPL's issue. Is the problem solved?

**Comment by arjarn** [comment]
Yes, I'm closing.

Thanx.
