### ISSUE TITLE
Using nested expansion panels and List Group causes error

### ISSUE THREAD

**Issue by nateshmbhat** [TheComputerM/svelte-materialify#80]
I am using 0.3.4 version of svelte-materialify
When i used nested expansion panels i get the following error : 

```js
Uncaught (in promise) TypeError: Cannot read property 'c' of undefined
    at transition_out (index.mjs:785)
    at Object.o (RpcSelector.svelte:25)
    at jt (index.mjs:1)
    at Object.o (index.mjs:3)
    at jt (index.mjs:1)
    at Object.p (index.mjs:3)
    at $t (index.mjs:1)
    at vt (index.mjs:1)
﻿
​```

Here's my svelte code : 

```svelte
<Container>
  <ExpansionPanels popout>
    {#each filenames as filename (filename)}
      <ExpansionPanel>
        <span slot="header">{filename}</span>
        <ExpansionPanels popout>
          {#each serviceNames as protoService (protoService)}
            <ExpansionPanel>
              <span slot="header">{protoService}</span>
            </ExpansionPanel>
          {/each}
        </ExpansionPanels>
      </ExpansionPanel>
    {/each}
  </ExpansionPanels>
</Container>

```

**Comment by TheComputerM** [comment]
Can you post the whole REPL code.

**Comment by nateshmbhat** [comment]
This is the exact code of the component. Click on the first expansion panel and click on it again to collapse. it causes an error and fails to expand or collapse any of the panels after that. 

```
<Container>
  <ExpansionPanels popout>
    {#each ['file1', 'file2', 'file3'] as protoFile (protoFile)}
      <ExpansionPanel>
        <span slot="header">{protoFile}</span>
        <ExpansionPanels popout>
          {#each ['serv1','serv2','serv3','serv4'] as protoService (protoService)}
            <ExpansionPanel>
              <span slot="header">{protoService}</span>
            </ExpansionPanel>
          {/each}
        </ExpansionPanels>

      </ExpansionPanel>
    {/each}
  </ExpansionPanels>
</Container>
```

**Comment by nateshmbhat** [comment]
Getting same error when i expand the "ListGroup" when using list group also : 

Here below is the code (whole svelte file content pasted below) that i copy pasted directly from svelte-materialify website : 

```svelte

<script lang="ts">
  import { List, ListGroup, ListItem, Icon } from 'svelte-materialify';

  let active = false;
</script>

<div class="d-flex justify-center">
  <List class="elevation-2" style="width:300px">
    <ListItem>
      <span slot="prepend">
        <Icon class="mdi mdi-home" />
      </span>
      Home
    </ListItem>
    <ListGroup bind:active offset={72}>
      <span slot="prepend">
        <Icon class="mdi mdi-cog" />
      </span>
      <span slot="activator"> Actions </span>
      <span slot="append">
        <Icon class="mdi mdi-chevron-up" rotate={active ? 0 : 180} />
      </span>
      <ListItem>Create</ListItem>
      <ListItem>Read</ListItem>
      <ListItem>Write</ListItem>
      <ListItem>Delete</ListItem>
    </ListGroup>
  </List>
</div>
```

I get the below error : 

```js
index.mjs:785 Uncaught (in promise) TypeError: Cannot read property 'c' of undefined
    at transition_out (index.mjs:785)
    at Object.o (RpcSelector.svelte:20)
    at jt (index.mjs:1)
    at Object.o (index.mjs:3)
    at jt (index.mjs:1)
    at Object.p (index.mjs:3)
    at $t (index.mjs:1)
    at vt (index.mjs:1)
```

**Comment by nateshmbhat** [comment]
let me know if you need anything , i will gladly help.

**Comment by nateshmbhat** [comment]
Found the issue. I was using an older version of svelte and ran into this issue : 
https://github.com/sveltejs/svelte/issues/3165
https://github.com/rob-balfre/svelte-select/issues/128

**Comment by TheComputerM** [comment]
Can you try with the advanced install?

**Comment by nateshmbhat** [comment]
Yes I have tried it. I can confirm that this issue is happening for all components which have some nesting.

When ever I have a conditional rendering ( if else block) to hide or show my components which consist of your components, I am getting this issue (not always though) .

**Comment by TheComputerM** [comment]
It is most probably a bug with svelte itself.

**Comment by nateshmbhat** [comment]
https://github.com/sveltejs/svelte/issues/3165#issuecomment-745782377

@TheComputerM please include the fix mentioned above in svelte-materialify. 
This will avoid issues for all the components.

**Comment by nateshmbhat** [comment]
Also , if i use the advanced install it's working when i import directly from "svelte-materialify/src" , since this would use the source files directly without the compiled ones.

**Comment by TheComputerM** [comment]
Even in the simple install we have svelte files already preprocessed using [this](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/preprocess.js) so I do not know what is causing the error.

**Comment by nateshmbhat** [comment]
Svelte has updated this fix in their latest version 3.32.0 . 
please update the svelte version

**Comment by TheComputerM** [comment]
It is now working, I do not need to update the svelte version as I only provide the source files.

**Comment by Florian-Schoenherr** [comment]
@nateshmbhat can this be closed?

**Comment by nateshmbhat** [comment]
when i import svelte from source directly , `import { Button } from 'svelte-materialify/src' , I get following typescript error : 

```
Could not find a declaration file for module 'svelte-materialify/src'. '/home/nateshmbhat/Desktop/tap-wire/node_modules/svelte-materialify/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/svelte-materialify` if it exists or add a new declaration (.d.ts) file containing `declare module 'svelte
```

**Comment by Florian-Schoenherr** [comment]
It says it in the message:
>   Try `npm i --save-dev @types/svelte-materialify`

Does that work?

**Comment by nateshmbhat** [comment]
no it doesn't work because the types of svelte-materialify are not present in npmjs.com/~types

**Comment by Florian-Schoenherr** [comment]
Sorry, I'm not really a ts fan, now I know that's not how it works..
I can only guess what the problem is, so here is a pointer:
https://github.com/edqx/sapper-materialify-repro/blob/master/tsconfig.json
He also imports from src.
If it still doesn't work, can you also try to import from just `svelte-materialify`?

**Comment by TheComputerM** [comment]
Did you try something with typeRoots?

**Comment by nateshmbhat** [comment]
I added a type definition file ( *.d.ts) and mentioned it in tsconfig in the includes parameter.

```
declare module 'svelte-materialify/src' {
  export 'svelte-materialify/@types'
} 
```

The above thing worked for me.

**Comment by marekdedic** [comment]
@Florian-Schoenherr Hi, since we're already discussing docs additions, the trick in last comment could definitely be useful there :D

**Comment by Florian-Schoenherr** [comment]
@marekdedic or #173
