### ISSUE TITLE
Icons not shown

### ISSUE THREAD

**Issue by PKrause79** [TheComputerM/svelte-materialify#81]
Hi,

I am trying this great materialify components, but was not able to show any icon on a button - is it a bug or did I do sth. wrong? I think I followed the documentation, and I was able to show the button but never the icon on it:

Code example on REPL playground:
https://svelte.dev/repl/d348852b828943db959caa46303925cc?version=3.31.0

```
  <script>
  	import { MaterialApp, AppBar, Divider, Button, Icon } from "svelte-materialify";
  </script>

  <MaterialApp>
	<AppBar>
		<div slot="icon">
			<Button fab>
			  <Icon class="mdi mdi-menu" />
			</Button>
		</div>
		<span slot="title">- left is a button without icon....</span>
	</AppBar>
	
	<Button fab>
			  <Icon class="mdi mdi-menu" /> 
	</Button>
	- here another button without icon
	
</MaterialApp>
```

Can you help me? Thanks in advance!

**Comment by TheComputerM** [comment]
https://svelte-materialify.vercel.app/components/icons/#types-of-icons
The Icon component is iconset agnostic, you can use any icon from any vendor you like. Just include thier icon font file if you want to use them.

**Comment by docseltsam** [comment]
I think the documentation is a bit misleading.

I use the aproach, by importing the package @mdi/js to my project and use the path prop of Icon component. 

If you follow this, your example source may look like following:

```
<script>
	import { mdiMenu } from '@mdi/js';
	import { MaterialApp, AppBar, Divider, Button, Icon } from "svelte-materialify";
</script>

<MaterialApp>
	<AppBar>
		<div slot="icon">
			<Button fab>
			  <Icon path={mdiMenu} />
			</Button>
		</div>
		<span slot="title">- left is a button without icon....</span>
	</AppBar>
	
	<Button fab>
			  <Icon path={mdiMenu} /> 
	</Button>
	- here another button without icon
	
</MaterialApp>
```

**Comment by PKrause79** [comment]
Runs well on the REPL playground - thanks a lot! 

On my own VSCode project I still had a problem due of lack of knowledge (bloody Svelte beginner) and documentation: additionally to this code it is needed to add a foreign NPM package "@mdi/js" to the project, by executing **"npm install @mdi/js"** on the shell! I think that is what @docseltsam talked about, too. Without that, Svelte will throw strange and confusing general errors regarding index.js...

Maybe I will find some time to help the team by preparing a PR for improving the Icon documentation - that the Icons will not work out of the box / additional packages are needed, that with that different icon sets are possible and that the path is the right attribute to configure an icon. 

THX! 👍

**Comment by TheComputerM** [comment]
The docs do really need to be more verbose. I wrote them all in a hurry.

**Comment by hoishing** [comment]
@PKrause79 if you want to use web font instead of svg, you may add the css link of material icon in your REPL
`<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@mdi/font@5.8.55/css/materialdesignicons.min.css" />
`

@TheComputerM I also can't show the icons when I was following the documentation. It will be nice if it tells the user to add CSS link when using web font.
