### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by avi12** [TheComputerM/svelte-materialify#83]
My `rollup.config.js` roughly looks like:
```js
import resolve from "@rollup/plugin-node-resolve";
import svelte from "rollup-plugin-svelte";
import { terser } from "rollup-plugin-terser";
import css from "rollup-plugin-css-only";
import preprocess from "svelte-preprocess";

const production = !process.env.ROLLUP_WATCH;

export default [{
  input: "src/popup.js",
  output: {
    format: "life",
    file: "dist/build/popup.js"
  },
  plugins: [
    css({ output: "bundle.css" }),
    svelte({
      compilerOptions: {
        dev: !production
      },
      preprocess: preprocess({
        scss: {
          includePaths: ["theme"]
        }
      })
    }),
    resolve({
      browser: true,
      dedupe: ["svelte"]
    }),
    production && terser()
  ],
  watch: {
    clearScreen: false
  }
}];
```
When running `rollup -w -c`, I'm getting:
```
"C:\Program Files\nodejs\node.exe" C:\Users\avi12\AppData\Roaming\npm\node_modules\pnpm\bin\pnpm.js run dev

> youtube-auto-hd-fps@1.3.0 dev C:\repositories\exte
nsions\youtube-auto-hd
> rollup -c -w

rollup v2.34.2
bundles src/popup.js → dist\build\popup.js...
[!] (plugin svelte) Error: Can't find stylesheet to
import.
   ╷
58 │ @import 'material-theme';
   │         ^^^^^^^^^^^^^^^^
   ╵
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\styles\_
variables.scss 58:9                     @use
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\styles\_
theme.scss 1:1                          @use
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\styles\_
global.scss 1:1                         @import
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\componen
ts\MaterialApp\MaterialApp.svelte 2:11  root stylesh
eet
node_modules\.pnpm\svelte-materialify@0.3.4_svelte@3
.30.1\node_modules\svelte-materialify\src\components
\MaterialApp\MaterialApp.svelte
Error: Can't find stylesheet to import.
   ╷
58 │ @import 'material-theme';
   │         ^^^^^^^^^^^^^^^^
   ╵
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\styles\_
variables.scss 58:9                     @use
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\styles\_
theme.scss 1:1                          @use
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\styles\_
global.scss 1:1                         @import
  node_modules\.pnpm\svelte-materialify@0.3.4_svelte
@3.30.1\node_modules\svelte-materialify\src\componen
ts\MaterialApp\MaterialApp.svelte 2:11  root stylesh
eet
    at Object._newRenderError (C:\repositories\exten
sions\youtube-auto-hd\node_modules\.pnpm\sass@1.30.0
\node_modules\sass\sass.dart.js:13478:19)
    at Object._wrapException (C:\repositories\extens
ions\youtube-auto-hd\node_modules\.pnpm\sass@1.30.0\
node_modules\sass\sass.dart.js:13321:16)
    at _render_closure1.call$2 (C:\repositories\exte
nsions\youtube-auto-hd\node_modules\.pnpm\sass@1.30.
0\node_modules\sass\sass.dart.js:79699:21)
    at _RootZone.runBinary$3$3 (C:\repositories\exte
nsions\youtube-auto-hd\node_modules\.pnpm\sass@1.30.
0\node_modules\sass\sass.dart.js:27088:18)
    at _FutureListener.handleError$1 (C:\repositorie
s\extensions\youtube-auto-hd\node_modules\.pnpm\sass
@1.30.0\node_modules\sass\sass.dart.js:25616:19)
    at _Future__propagateToListeners_handleError.cal
l$0 (C:\repositories\extensions\youtube-auto-hd\node
_modules\.pnpm\sass@1.30.0\node_modules\sass\sass.da
rt.js:25913:49)
    at Object._Future__propagateToListeners (C:\repo
sitories\extensions\youtube-auto-hd\node_modules\.pn
pm\sass@1.30.0\node_modules\sass\sass.dart.js:4539:7
7)
    at _Future._completeError$2 (C:\repositories\ext
ensions\youtube-auto-hd\node_modules\.pnpm\sass@1.30
.0\node_modules\sass\sass.dart.js:25746:9)
    at _AsyncAwaitCompleter.completeError$2 (C:\repo
sitories\extensions\youtube-auto-hd\node_modules\.pn
pm\sass@1.30.0\node_modules\sass\sass.dart.js:25089:
12)
    at Object._asyncRethrow (C:\repositories\extensi
ons\youtube-auto-hd\node_modules\.pnpm\sass@1.30.0\n
ode_modules\sass\sass.dart.js:4288:17)
```

**Comment by TheComputerM** [comment]
Did you create a `_material-theme.scss` file and place it in a folder called theme respective to the root of the project?

**Comment by avi12** [comment]
I didn't, I hoped to merely rely on Svelte Materialify's themes as I don't intend to change the defaults

**Comment by avi12** [comment]
Update: I think that the problem is that Svelte for some reason is failing to import `./nouislider.min.js` using
```js
import noUiSlider from "./nouislider.min";
```
If I'm correct, all you've got to do is to add to the import statements' filesnames `.js`

**Comment by TheComputerM** [comment]
I don't think it is that, you can see it identifies the path
```
'default' is not exported by node_modules\.pn
pm\svelte-materialify@0.3.4_svelte@3.30.1\node_modul
es\svelte-materialify\src\components\Slider\nouislid
er.min.js
```
I cannot understand the problem as I updated my dependencies and tried it and it still works.

**Comment by avi12** [comment]
Made an [example repo](https://github.com/avi12/svelte-materialify-test), and I bet I'm configuring something wrong since now I'm getting a different error

**Comment by avi12** [comment]
I also tried adding a [yarn](https://github.com/avi12/svelte-materialify-test/tree/yarn) branch, and this time I'm also getting a different error
Note that I'm using there Yarn 1.22.5

**Comment by bRRRITSCOLD** [comment]
Not saying this helps in any way! Just saying I noticed a problem similar to the original error described - I posted this in the svelte discord channel also:

I noticed the same bug with the _material_theme.scss file in my first project with svelte-materialify.  To get around this I ended up having to create a _material_theme.scss file in the ROOT folder and not a theme folder. I started a second project with nothing more then npx degit, npm install, scripts/setupTypeScript, and npm install --save svete-materialify with a theme folder + _material_theme.scss file and it worked with no probelms. I think the other thing was that in the second project too, in my App.svelte file,  I wrapped everything in the MaterialApp component from svelte-materialify. See if this gets you anywhere. Start very basic, nothing more than svelte and svelte-materialify, and work your way up. That is how I solved it. Example working repo with theme/_material_theme.scss - https://github.com/bRRRITSCOLD/blainerrichardson.cloud, and here is an example that wouldnt work unless I created file in ROOT folder https://github.com/bRRRITSCOLD/winston-daily-rotate-file-admin-tauri (the bug I described above) - I couldnt find the difference either.... Basically gave up, started fresh, both on a Svelte and App level. That is a crap ton to take in. Lmk if you have questions dood

**Comment by bRRRITSCOLD** [comment]
"I think the other thing was that in the second project too, in my App.svelte file,  I wrapped everything in the MaterialApp component from svelte-materialify" - looked deeps/investigated and I fount that I wrapped both of them in a MaterialApp component. So, the only diffs are packages and folder/file structure/placement. Still, I hope it helps.

**Comment by TheComputerM** [comment]
This should be called `_material-theme.scss` https://github.com/avi12/svelte-materialify-test/blob/main/theme/_svelte-materialify.scss

**Comment by TheComputerM** [comment]
Issue has been resolved.

**Comment by Florian-Schoenherr** [comment]
@bRRRITSCOLD 
![postcss](https://user-images.githubusercontent.com/65456722/102875494-28ecbb00-4444-11eb-84bb-5ffdb74ccac3.png)
I think `postcss` should have been `scss`, I thought I already wrote you that on discord (?)

**Comment by bRRRITSCOLD** [comment]
Yes you did write me in discord. Unfortunately you are incorrect. In the repo (https://github.com/bRRRITSCOLD/blainerrichardson.cloud) that I made after you communicated in Discord, I use scss and it works perfectly fine. I was just simply sharing my experience with this fellow as I put him on to your library. Sorry for the promotion and confusion.

**Comment by Florian-Schoenherr** [comment]
Oh yeah, I meant on https://github.com/bRRRITSCOLD/winston-daily-rotate-file-admin-tauri.
There, on every commit you had `postcss`. Maybe that's not even a problem / something else is wrong. I was just guessing :)
Also, nothing to be sorry about, I just remembered the problem and wanted to clarify 👍
