### ISSUE TITLE
Use of global styles (+MaterialApp without header styles)

### ISSUE THREAD

**Issue by MuhsinFatih** [TheComputerM/svelte-materialify#91]
Using any svelte-materialify component in an app applies global changes to the document style. Would it be possible to scope all styles to `MaterialApp` so the 'non-material' parts of the app are uneffected?

**Comment by TheComputerM** [comment]
Use can use the `.s-${component}` seletors, like `.s-btn` to only target material buttons and `.s-btn.fab` to only target fab material buttons.

**Comment by Florian-Schoenherr** [comment]
@MuhsinFatih it's a component-framework problem:
if we scope it, nobody can change our styles because the svelte compiler adds random letters/numbers onto the class.
This would only work with conservative classes and options to add styles (because `style` has higher specificity)..
maybe there are also performance differences..
You will probably not use the same class-names, so it's okay unless you have a specific use-case, then tell us.

**Comment by FunMiles** [comment]
I have an objection related to the OP's issue. I have found that the inputs are affected by a style that imposes a width of 100% screwing up more detailed layout. Here is an example. I have developed an app using React and material-ui for react. There is an input screen that needs to run on a variety of devices. When the device has a wide screens, some inputs are in `div` that should let them be side by side. If the screen is narrow, they go on top of one another.
Here are partial screen shots with React material-ui:
Wide screen:
<img width="570" alt="Screen Shot 2020-12-31 at 9 08 06 AM" src="https://user-images.githubusercontent.com/7741038/103417846-9a65f100-4b49-11eb-84a6-475194eea4a1.png">
Narrow screen:
<img width="410" alt="Screen Shot 2020-12-31 at 9 07 41 AM" src="https://user-images.githubusercontent.com/7741038/103417868-abaefd80-4b49-11eb-8bcb-e8e476c46bd6.png">

Here is my attempt using svelte-materialify:
Wide screen:
<img width="543" alt="Screen Shot 2020-12-31 at 9 10 27 AM" src="https://user-images.githubusercontent.com/7741038/103417911-da2cd880-4b49-11eb-89bf-0d91e15662d4.png">
Narrow screen:
<img width="278" alt="Screen Shot 2020-12-31 at 9 10 01 AM" src="https://user-images.githubusercontent.com/7741038/103417916-e31daa00-4b49-11eb-9bac-2fbd31f9f5c3.png">

So no matter how wide the screen is, the input takes the whole width and consecutive ones come over one another and never side by side.
It seems my problem might be rooted in some overly broad size styling:
<img width="330" alt="Screen Shot 2020-12-31 at 9 26 21 AM" src="https://user-images.githubusercontent.com/7741038/103417985-41e32380-4b4a-11eb-8d0c-aa7cd05c7e13.png">

I am a not super-experienced with CSS and I personally find CSS extremely difficult to debug. Maybe I am identifying things incorrectly, but unless someone sees a glaring error I am making, I am suggesting that styling should try to minimize their effect strictly to the local component and try to avoid interfering with how the components is going to be layed out with respect with other components. I am not sure how react's material-ui does it. It only took me a minute to get what I wanted. Here, I am struggling.

**Comment by MuhsinFatih** [comment]
@TheComputerM what I mean is that the library changes basic styles and that leaks out to the parents. For example:

![image](https://user-images.githubusercontent.com/8341386/103423481-d2365e00-4b74-11eb-9302-7bab6b02587d.png)

In this image there is a parent div with the green text in it. There's a child svelte component with the red text and the clock.
As soon as I import svelte-materialify and create a button inside the child component:

```
<MaterialApp theme="{theme}">
	<Button>Click!</Button>
</MaterialApp>
```

Both the green and red `h1`s get much bigger:
![image](https://user-images.githubusercontent.com/8341386/103423506-f42fe080-4b74-11eb-9b1b-3b6078c213c8.png)

If you scoped all the styles, but used css variables for all of them, wouldn't we still be able to theme it by changing the css variables?

My problem right now is that I've created a lot of components and I need to add them to an existing project. However as soon as I add my components the original project style goes haywire. Is there a simple solution to this? Like, can I tell svelte to scope one component's all styles to within itself?
Ok this part is a little sidetracking, but even more specifically, I'm trying to add my components inside a react app by converting the svelte components into web-components. In the image above, the child component actually is a web component. I've done a lot of debugging and reduced the problem to the use of `global` operator. If a component uses that, the global style leaks even outside the shadow dom

**Comment by MuhsinFatih** [comment]
This question is actually not only subject to this library, but a more general problem. I've created a stackoverflow question where I described this in its more general form: https://stackoverflow.com/questions/65525183/scope-svelte-component-styles-even-when-global-operator-is-used  
I'm only mentioning this because if there's a more general solution where I can tell svelte to scope a component and all of its child styles and not leak anything, then I suppose it could make this issue obselete

**Comment by Florian-Schoenherr** [comment]
@FunMiles I had some problems like this too, in your specific case you can use a flex-container with `flex-direction: row` around the inputs. I guess it depends and maybe we could do less styling but provide defaults for `export let class`?

**Comment by TheComputerM** [comment]
This [RFC](https://github.com/sveltejs/rfcs/blob/master/text/0000-style-properties.md) might help for general use cases.

**Comment by TheComputerM** [comment]
You can also change variables such as [here](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/styles/_variables.scss) to better style your pages.

**Comment by FunMiles** [comment]
@Florian-Schoenherr  `display: flex; flex-direction: row;` does give me what I want.
There is a small issue overall with the `TextField`. The label on top does flow out of the `TextField` box. 
And one little improvement that comes for the react material-ui equivalent, would be to hide the placeholder text when the box is empty and not active. Move the label to its position above then the box has focus and then the placeholder appears.
Maybe those two issues should be reported in another `issue`.

**Comment by Florian-Schoenherr** [comment]
@FunMiles I don't exactly know what you mean, but yes, another issue please. (react material-ui looks the same to me, add a screenshot in the issue)

**Comment by FunMiles** [comment]
@Florian-Schoenherr See issue #93

**Comment by MuhsinFatih** [comment]
I've been looking more into the source code, I noticed that the `:global` operator is actually not used. The styles are defined in `src/styles`, and I found the `h1` style for example which I used in the example above:
https://github.com/TheComputerM/svelte-materialify/blob/b98e987182195305f4e1ea934b3e3bca932260b7/packages/svelte-materialify/src/styles/_variables.scss#L85-L94

and the styles are imported in here:  
https://github.com/TheComputerM/svelte-materialify/blob/b98e987182195305f4e1ea934b3e3bca932260b7/packages/svelte-materialify/src/components/MaterialApp/MaterialApp.svelte#L5-L7

Since the styles are defined in `MaterialApp.svelte`, it seems like the intention was to scope all styles to `MaterialApp` and its children. But there's a `global` operator in line 5. I couldn't find any documentation as to what `global` does as a style tag attribute, but my guess is that it makes everything inside global. Removing it and building the library made all the styles disappear as expected, both for parents and for children. Could it be made to scope only to children, not globally?

Something like this which I can do **inside** the style tag:
```css
* :global(*) {
	color: goldenrod;
}
/* notice the '*' before 'global', which scopes the style to the children of everything inside that component, 
and the second '*' to scope to everything. So it's "all the children of all my children" */
```
This children scoping is explained in the docs:
https://svelte.dev/docs#style

@Florian-Schoenherr I think I now understand what you meant by this comment:


> @MuhsinFatih it's a component-framework problem:
> if we scope it, nobody can change our styles because the svelte compiler adds random letters/numbers onto the class.
> This would only work with conservative classes and options to add styles (because `style` has higher specificity)..
> maybe there are also performance differences..
> You will probably not use the same class-names, so it's okay unless you have a specific use-case, then tell us.
> I guess related: #31

I looked at the style files, and almost all styles are with class names like you said. However there are opinionated defaults like `h1`, `input` etc which effect everything regardless of classname. If those were also made to use classnames, this problem would be solved. I am guessing that that will take a little time though. I need to ship my components asap, is there a quick workaround I can do to scope the imported styles to `MaterialApp`?

**Comment by TheComputerM** [comment]
@MuhsinFatih We do not add class names to everything as it would make it slow (see CSS selector benchmark) and would be irritating to many people. I suggest you create your own `MaterialApp.svelte` where you can import whatever scss files you like.

**Comment by TheComputerM** [comment]
If you do not want styles for heading then do NOT import the [_headings.scss](https://github.com/TheComputerM/svelte-materialify/blob/master/packages/svelte-materialify/src/styles/elements/_headings.scss) file.

**Comment by FunMiles** [comment]
I didn't find where this was posted originally, but I thought I'd make a comment as it might help @MuhsinFatih:
> @MuhsinFatih it's a component-framework problem:
if we scope it, nobody can change our styles because the svelte compiler adds random letters/numbers onto the class.
This would only work with conservative classes and options to add styles (because style has higher specificity)..
maybe there are also performance differences..

Svelte does not add random letters/numbers to the given class names/ids. It adds its own class and then scopes the rule to the combination of the two classes or class and id.
Here is an example of that:

I created a class 'horizontal' to do what @Florian-Schoenherr had suggested in an earlier post:
```css
.horizontal {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
    }
```
I then have the following HTML:

```html
<div class='horizontal'>
    <TextField.../>
    <TextField.../>
</div>
```

The result svelte created are:
```css
.horizontal.svelte-o1hm95 {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
}
```
and
```html
<div class="horizontal svelte-o1hm95">
    <TextField.../>
    <TextField.../>
</div>
```

Maybe understanding this might help you, @MuhsinFatih since you can target any such class (for example my 'horizontal') globally with something like
```css
<style>
:global(.horizontal) {
    background-color: red;
}
</style>

**Comment by FunMiles** [comment]
For some of issues of full app theming, why not use css or js variables that could be set on the App.svelte side?
The react material-ui introduces some specific 'theming' functions to recover or set colors to be used downstream. Maybe that'd be a good approach here for a lot of theming/detailed controls?

**Comment by Florian-Schoenherr** [comment]
@FunMiles oh. I learned something new. Ok it really adds its own class huh.. sorry oops

**Comment by Florian-Schoenherr** [comment]
> @MuhsinFatih We do not add class names to everything as it would make it slow (see CSS selector benchmark) and would be irritating to many people. I suggest you create your own `MaterialApp.svelte` where you can import whatever scss files you like.

Why not make heading-styles optional somehow? Can we not have something like an `UnopinionatedMaterialApp.svelte`?
Or if there is some sort of "global" with which you can add header styles etc. we could conditionally enable it on MaterialApp - so `{if opinionated}<HeaderStyles/>{/if}`.
Right now I also just overwrite svelte-materialify header-styles with higher specificity.

**Comment by MuhsinFatih** [comment]
I've been playing around with this all day and achieved what I wanted. I also don't see any extra generated classnames, am I missing something? 😄 
![image](https://user-images.githubusercontent.com/8341386/103484414-b58c6700-4dbc-11eb-9dbd-27c452980c24.png)

What I did is I changed all the styles to use the descendant operator with `s-app` as ancestor. For example:
```scss
// before
p {
  margin-bottom: $spacer * 4;
}

// after
.s-app p {
  margin-bottom: $spacer * 4;
}
```

There are a few edge cases like body and html styles which I replaced with `s-app`. Is there any downside to this implementation?

**Comment by FunMiles** [comment]
@MuhsinFatih I think that the no extra classnames is due to the use of the `global` in the source code `style` that you mentioned earlier. I did a search on global use in that context yesterday and did find some details. I'll try to find that again and attach a link.

**Comment by MuhsinFatih** [comment]
@FunMiles yea the styles are still global, but instead of scoping with svelte's abstraction, what I did was to scope with css. Although I don't know if the descendant operator effects the performance significantly. If you can point me in the right direction to benchmark on this repo with the changes, I can definitely give it a go

**Comment by FunMiles** [comment]
@MuhsinFatih, regarding the performance that @TheComputerM was talking about I found some information that seems to indicate that [the thinking is outdated and that you should not concern yourself with one mode of selection vs another.](https://ecss.io/appendix1.html)
Personally, and maybe this is for the kind of application I do, I think that svelte provides all the tools to make the DOM size small enough that any DOM operation (including references) very inexpensive. Compared to React, for example, the svelte's version of a dynamic virtual list is amazingly simple and small and the resulting DOM impact is tiny. (I compared the 'react-window' vs 'svelte-virtual-list')

**Comment by TheComputerM** [comment]
I am going to answer some questions

> Since the styles are defined in MaterialApp.svelte, it seems like the intention was to scope all styles to MaterialApp and its children.

Nah, there are at least a hundred selectors in the global css and if each one would start with `.s-app` it would increase the file size and make the app slow. We could scope the element selectors (such as h1,h2,p,blockquote) though, but such a use case is very rare as all the styles are customizable and everything you do is inside a `MaterialApp`.

> Why not make heading-styles optional somehow? Can we not have something like an UnopinionatedMaterialApp.svelte?

Nice idea! The minimal version would not have any extra helper and extra styles attached to it.

> I found some information that seems to indicate that the thinking is outdated and that you should not concern yourself with one mode of selection vs another.

I seemed to have misunderstood, pls read my response to the first question.

> For some of issues of full app theming, why not use css or js variables that could be set on the App.svelte side?

As per my knowledge, they seem to use css-in-js solutions which is just not required in svelte, I am going to migrate svelte-materialify from sass to postcss so we can change variables in js files instead of scss ones and also purge unused classes.

Any other questions?

**Comment by dmitrioligy** [comment]
I recently ran into the problem of MaterialApp and Material Component styles leaking into the parent app, which has different styling. I would normally assume all svelte-materialify styling should remain within the components only, and optionally allow utility classes (colors, fonts, shadows etc) be available per some option.

I was able to use the solution
```
<style lang="scss" global>
    .horizontal {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
    }
</style>
```
With a minor modification

```
// src/styles/global.scss
body {
    /* Whatever global styles I need applied */
}
h1 {
   /* More custom styling */
}

// _layout.svelte
<style lang="scss" global>

    @import '../styles/global.scss';

</style>

```


I am sure there is a config for preprocess in svelte.config.js that can be set up, but I didn't debug far into preprocess config order of execution. If anyone has an easier way to do so, please drop a comment.
But I still do think that utility classes from svelte-materialify should remain optional, not intruding in global css space that was predefined before. Overwriting using this lang='scss' global method overwrites already existing css from svelte-materialify, and makes the element css cluttered with overwritten classes. Please correct me where I am wrong! Looking for any feedback.

**Comment by Renkas** [comment]
This is absolutely annoying ... 

And to add to the confusion this "feature" is creating it's not even working like this in all cases. For example:

Have Sapper setup. Use component from `svelte-materialify` only on one page, let's say `index.svelte`. When you navigate to other pages `About` etc - they have inherited styles that I have not intended to use.
But now - if you refresh the page on `About` page, then these styles are not loaded. But they are loaded as soon as you visit `Index` again. So this behaviour is not even consistent ...

**Comment by Florian-Schoenherr** [comment]
See #136

**Comment by Florian-Schoenherr** [comment]
I've finally made it "a little" easier to work without headers and helper styles. We will (soon) have some major changes in this regard, no more global (if it works out).

**Comment by V-ed** [comment]
Just got hit by this trying to figure out why Tailwind CSS's utility classes (`mt-2 sm:mt-0`, particularily the `sm:mt-0` here) didn't work, until I finally realized that Materialify's own styling utils were overriding Tailwind's generated classes.

Subscribed to https://github.com/TheComputerM/svelte-materialify/issues/136 in the hope that `MinimalMaterialApp` comes out sooner than later!

**Comment by Florian-Schoenherr** [comment]
@V-ed it is, see MaterialAppMin

**Comment by V-ed** [comment]
> @V-ed it is, see MaterialAppMin

It doesn't seem there in the latest version...

![image](https://user-images.githubusercontent.com/16652915/114404338-9b101980-9b73-11eb-9158-5c2fc05ae872.png)
