### ISSUE TITLE
helprequest: How can I get a menu item push event?

### ISSUE THREAD

**Issue by UedaTakeyuki** [TheComputerM/svelte-materialify#92]
Thank you for your great job!
This has a great UI with easy to understand documents. 

Just one thing, I'm stacking that I can't get a menu item push event.

I've created a following menu:
```
  <Menu right>
    <div slot="activator">
      <Button fab depressed>
        <Icon class="mdi mdi-dots-vertical" />
      </Button>
    </div>
    <List>
      <ListItem on:click={console.log("Home")}>Home</ListItem>
      <ListItem on:click={console.log("Account")}>Account</ListItem>
      <ListItem on:click={console.log("Admin")}>Admin</ListItem>
    </List>
  </Menu>
```

I'm expecting that I can get **click** event when I crick each **listitem**, but real result is that I get all 3 click event at the time of menu open.

So, what was correct way to get menu push event? Thank you for your help.

**Comment by Florian-Schoenherr** [comment]
@UedaTakeyuki 
You need to pass a javascript function to on:click, so in your case:
`() => console.log("Home")`

**Comment by UedaTakeyuki** [comment]
Hi @Florian-Schoenherr

Thank you for your suggestion!
I've tried it as [here](https://github.com/UedaTakeyuki/template4SvelteMaterialify/blob/7de8921a052b359aad4a88c1511064e1020830bb/src/components/AppBar.svelte#L37). But any event was not issued even I've clicked a menu item.

For reference, the code repository that issue reproducing is as [here](https://github.com/UedaTakeyuki/template4SvelteMaterialify), and it is deployed to the Netlify at [here](https://infallible-pike-732f37.netlify.app/)

**Comment by Florian-Schoenherr** [comment]
@UedaTakeyuki I set `margin-top: 300px;` on your `.body`-class, that freed up the Menu.
No idea what the solution could be, but essentially the problem is that when you click the menu-item, you actually are clicking on the `<h1>Home</h1>`. That's also why the cursor doesn't change to `pointer`.
Does you h1 have a click-handler? That could also be the problem.

**Comment by UedaTakeyuki** [comment]
So, for now, my understanding that the click event of the menu items is captured by **<h1>Home</h1>** and no way to get it except clearing the same height as the menu by **margin-top**.

Do you mind If I close this help request and make a new bug report as "The click event of menu items in the appbar is captured by body element"?

**Comment by Florian-Schoenherr** [comment]
No, you can keep this one open. I just gave my 2 cents, @TheComputerM will maybe have another idea.
Can you edit the title of this one instead?
So you really have a click-handler on `<h1>Home</h1>` or on `<body>`?

**Comment by UedaTakeyuki** [comment]
I've add click-handler to h1 as `<h1 on:click={() => console.log("h1:home")}>Home</h1>` and to body as `<div style="position:relative;" on:click={() => console.log("body")} class="body">`.

When I clicked the menu item, the console log is as:

```
h1:home
body
```

It seems body and h1 capture click event.

**Comment by TheComputerM** [comment]
Have you tried `on:click|self`?

**Comment by UedaTakeyuki** [comment]
`on:click:sefl` to h1 and body as follows?

`<h1 on:click|self>Home</h1>`
`<div style="position:relative;" on:click|self class="body">`

The result of clicking menu item is nothing returned.

**Comment by UedaTakeyuki** [comment]
With added `style="position:relative;z-index:1;"` to **AppBar**, I can get click event from menu item

`<AppBar style="position:relative;z-index:1;">`

**Comment by Florian-Schoenherr** [comment]
@UedaTakeyuki if you remove `position: relative;` from .body it works, too

**Comment by UedaTakeyuki** [comment]
Thank you @Florian-Schoenherr, but `position: relative;` of .body is necessary for `overlap` for `NavigationDrawer` to avoid the .body is pushed down by the navigation drawer.
I'd like to use NavigationDrawer that doesn't push down the .body like **Vuetify NavigationDrawer**...

**Comment by Florian-Schoenherr** [comment]
No idea why it's pushed down, or what you mean.
Maybe take a look at this, it's the svelte-materialify docs layout https://github.com/TheComputerM/svelte-materialify/blob/master/packages/docs/src/routes/_layout.svelte

**Comment by UedaTakeyuki** [comment]
I should apologize to you that "pushed down" was my confusion. Yes, your pointing is absolutely working for me.

Finally, removed **overlay** and **body** I can get well working **Navigationdrawer** and dropdown menu, thank you for your patient support for me!
