### ISSUE TITLE
Dev server needs update to work

### ISSUE THREAD

**Issue by DinCahill** [TheComputerM/svelte-materialify#96]
`yarn dev` didn't work for me at first, but after a `yarn upgrade` everything seemed to work 🙂 .
Tested on Ubuntu 20.04, nvm, node lts 14 and 12.

```
docs: $ sapper dev --ext ".svelte .md"
docs: ✗ client
docs: Cannot read property 'length' of undefined
docs: ✗ server
docs: Cannot read property 'length' of undefined
docs: internal/modules/cjs/loader.js:883
docs:   throw err;
docs:   ^
docs: Error: Cannot find module '/home/din/source/svelte-materialify/packages/docs/__sapper__/dev/server/server.js'
docs:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
docs:     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
docs:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
docs:     at internal/main/run_main_module.js:17:47 {
docs:   code: 'MODULE_NOT_FOUND',
docs:   requireStack: []
docs: }
docs: > Server crashed
```

**Comment by TheComputerM** [comment]
Sometimes sapper gets incorrectly installed, I tried to run the server on my laptop and it worked without me updating the dependencies.

**Comment by DinCahill** [comment]
I've found that it works after running `yarn upgrade-interactive` and upgrading `svelte 0.30.0 -> 0.31.1`. Or, change svelte version for root and svelte-materialify, and run `yarn`. I tried too 0.30.1, but it used 0.31.1 anyway.

I tried on Windows and it's the same. Am I doing something wrong?

**Comment by TheComputerM** [comment]
No, the sapper installation is sometimes buggy, you can find many such problems on the official sapper repo. They reinstalled and it worked.
