### ISSUE TITLE
Select displays item value instead of item name

### ISSUE THREAD

**Issue by cendro93** [TheComputerM/svelte-materialify#98]
I know issue like this was closed but there was a discussion there.
I think Select component should display in the text field exactly what the user have chosen in menu.
```
const items = [
{ name: 'Bike', value: 1 },
{ name: 'Car', value: 2 },
{ name: 'Train', value: 3 },
];
<Select outlined {items}> Outlined
```
How can i 'hold' hidden value of a 'Bike' which is 1 without showing it to a user ?

[Link to the previous issue in this matter](https://github.com/TheComputerM/svelte-materialify/issues/77)

**Comment by TheComputerM** [comment]
Closing this one and reopening the other.
